namespace RimeLib.Frostbite.Bundles.Entries
{
    /// <summary>
    /// Abstract class representing a resource
    /// </summary>
    public abstract class Resource : EntryBase
    {
        /// <summary>
        /// Name of the resource
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Type hash of the resource, can be generated by using RimeHelper.HashLowerCase
        /// </summary>
        public ResourceType TypeHash { get; set; }

        /// <summary>
        /// Metadata about the resource
        /// </summary>
        public byte[] Meta { get; set; }
    }
}
