///////////////////////////////////////////////////////////////
//                                                           //
// This is an automatically generated file.                  //
// Do *NOT* modify unless you really know what you're doing. //
//                                                           //
///////////////////////////////////////////////////////////////

using RimeLib.IO;
using RimeLib.Frostbite.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.Reflection;
using RimeLib.Serialization.Attributes;
using RimeLib.Serialization.Containers;
using RimeLib.Serialization.Ebx;

namespace fb
{
	[ContainerType(Flags: 137, Size: 4  )]
	public enum StatEvent : int
	{
		StatEvent_Kill = 0,
		StatEvent_Kill_In_X = 1,
		StatEvent_Kill_As_X = 2,
		StatEvent_KillWith_X_As_Y = 3,
		StatEvent_KillDistance = 4,
		StatEvent_KillOf_X_As_Y = 5,
		StatEvent_KillOf_X_In_Y = 6,
		StatEvent_TeamKill = 7,
		StatEvent_AvengerKill = 8,
		StatEvent_SaviorKill = 9,
		StatEvent_DriverAssist = 10,
		StatEvent_TeamDriverAssist = 11,
		StatEvent_SquadDriverAssist = 12,
		StatEvent_PassengerAssist = 13,
		StatEvent_TeamPassengerAssist = 14,
		StatEvent_SquadPassengerAssist = 15,
		StatEvent_RoadKill = 16,
		StatEvent_Death = 17,
		StatEvent_DoubleKill = 18,
		StatEvent_TripleKill = 19,
		StatEvent_MultiKill = 20,
		StatEvent_PostMortemKill = 21,
		StatEvent_KillStreak = 22,
		StatEvent_KillStreakX = 23,
		StatEvent_CancelKillStreak = 24,
		StatEvent_Comeback = 25,
		StatEvent_SquadWipe = 26,
		StatEvent_NemesisKill = 27,
		StatEvent_NemesisKillX = 28,
		StatEvent_CancelNemesisKill = 29,
		StatEvent_SecondsAs_X = 30,
		StatEvent_SecondsWith_X = 31,
		StatEvent_SecondsIn_X = 32,
		StatEvent_SecondsOn_X = 33,
		StatEvent_Destroy_X = 34,
		StatEvent_Destroy_X_As_Y = 35,
		StatEvent_Destroy_X_In_Y = 36,
		StatEvent_DestroyWith_X_As_Y = 37,
		StatEvent_Destroy_X_With_Y = 38,
		StatEvent_DestroyExplosives = 39,
		StatEvent_Disabled_X = 40,
		StatEvent_KillOfWith_X_As_Y = 41,
		StatEvent_TaggedDamageAssist_X = 42,
		StatEvent_Tagged_X = 43,
		StatEvent_SuppressWith_X_As_Y = 44,
		StatEvent_Level_X_Completed_Y_Difficulty = 45,
		StatEvent_Level_X_Completed_Y_Difficulty_WithTimeValue = 46,
		StatEvent_CleanLevel_X_Completed = 47,
		StatEvent_RoundOverOutcome_X_On_Y = 48,
		StatEvent_Rounds = 49,
		StatEvent_Headshot_X_With_Y = 50,
		StatEvent_HeadshotAs_X_With_Y = 51,
		StatEvent_HeadshotDistance_With_X = 52,
		StatEvent_SelfHeal = 53,
		StatEvent_BestSquad = 54,
		StatEvent_ShotsFired_With_X = 55,
		StatEvent_ShotsHit_With_X = 56,
		StatEvent_SpotAssist = 57,
		StatEvent_SpotAssistFrom_X = 58,
		StatEvent_SuppressionAssist = 59,
		StatEvent_Heal = 60,
		StatEvent_TeamHeal = 61,
		StatEvent_SquadHeal = 62,
		StatEvent_Revive = 63,
		StatEvent_TeamRevive = 64,
		StatEvent_SquadRevive = 65,
		StatEvent_ReviveAccepted = 66,
		StatEvent_TeamReviveAccepted = 67,
		StatEvent_SquadReviveAccepted = 68,
		StatEvent_ManDownRevive = 69,
		StatEvent_Resupply = 70,
		StatEvent_TeamResupply = 71,
		StatEvent_SquadResupply = 72,
		StatEvent_KillAssist = 73,
		StatEvent_Repair = 74,
		StatEvent_TeamRepair = 75,
		StatEvent_SquadRepair = 76,
		StatEvent_VehicleDestroyAssist = 77,
		StatEvent_TreeDestroyed = 78,
		StatEvent_WallDestroyed = 79,
		StatEvent_CaptureCapturePoint = 80,
		StatEvent_CaptureCapturePointAssist = 81,
		StatEvent_NeutralizeCapturePoint = 82,
		StatEvent_NeutralizeCapturePointAssist = 83,
		StatEvent_CapturePointDefense = 84,
		StatEvent_CapturePointAttack = 85,
		StatEvent_CrateArmed = 86,
		StatEvent_CrateDisarmed = 87,
		StatEvent_CrateDestroyed = 88,
		StatEvent_CrateDefendKill = 89,
		StatEvent_CrateAttackKill = 90,
		StatEvent_SquadDefendOrder = 91,
		StatEvent_SquadAttackOrder = 92,
		StatEvent_SquadLeaderDefendOrder = 93,
		StatEvent_SquadLeaderAttackOrder = 94,
		StatEvent_RankUp = 95,
		StatEvent_UniqueAward = 96,
		StatEvent_DogTag = 97,
		StatEvent_DogTagSavior = 98,
		StatEvent_SquadSpawn = 99,
		StatEvent_SquadSpawnOnRemoteVehicle_X = 100,
		StatEvent_Suicide = 101,
		StatEvent_GainAward_X = 102,
		StatEvent_PlayerScoreboardPosition_X = 103,
		StatEvent_GainedHighestRank = 104,
		StatEvent_GainedHighestUnlockInBucket_X = 105,
		StatEvent_Misc_X_and_Y = 106,
		StatEvent_TotalScoreOn_X_Difficulty_Y = 107,
		StatEvent_Invalid = 108,
		StatEvent_Damage = 109,
		StatEvent_PlayerScoreboardPosition_X_On_Y = 110,
		StatEvent_CaptureCapturePointDOM = 111,
		StatEvent_CaptureCapturePointAssistDOM = 112,
		StatEvent_NeutralizeCapturePointDOM = 113,
		StatEvent_NeutralizeCapturePointAssistDOM = 114,
		StatEvent_Kill_With_X_In_Y = 115,
		StatEvent_DoubleKill_With_X_In_Y = 116,
		StatEvent_ShotFired_With_X = 117,
		StatEvent_SpotAssistFor_X = 118,
		StatEvent_Misc_X_In_Y = 119,
		StatEvent_CTF_Capture = 120,
		StatEvent_CTF_CaptureStreak = 121,
		StatEvent_CTF_CaptureAssist = 122,
		StatEvent_CTF_PickUp = 123,
		StatEvent_CTF_PickUpAssist = 124,
		StatEvent_CTF_Return = 125,
		StatEvent_CTF_CarrierAssist = 126,
		StatEvent_CTF_CarrierAssistStreak = 127,
		StatEvent_CTF_FlagTransporter_In_X = 128,
		StatEvent_CTF_CarrierSavior = 129,
		StatEvent_CTF_CarrierSuppression = 130,
		StatEvent_CTF_CarrierKiller = 131,
		StatEvent_CTF_CarrierKillAssist = 132,
		StatEvent_CTF_CarrierHeal = 133,
		StatEvent_BadLuck = 134,
		StatEvent_Jump_In_X = 135,
		StatEvent_Kill_From_X = 136,
		StatEvent_ParadropDestroy_X = 137,
		StatEvent_ParadropKill = 138,
		StatEvent_FreefallDeath = 139,
		StatEvent_PassengerKill_In_X = 140,
		StatEvent_TakeDogTagAssassin = 141,
		StatEvent_Spawn_In_X = 142,
		StatEvent_RoadKill_With_X = 143,
		StatEvent_LAST_ITEM = 144
	}

}
