<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
      <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="SharpGLTF.Toolkit">
        <HintPath>..\..\..\.nuget\packages\sharpgltf.toolkit\1.0.5\lib\net8.0\SharpGLTF.Toolkit.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
