using fb;
using RimeLib.Content.Mounting;
using RimeLib.Extensions;
using RimeLib.Frostbite;
using RimeLib.Frostbite.Core;
using RimeLib.IO;
using RimeLib.IO.Conversion;
using RimeLib.Math;
using SharpGLTF.Schema2;
using SharpGLTF.Materials;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using SharpGLTF.Geometry;
using SharpGLTF.Geometry.VertexTypes;
using RimeLib.Mesh.Frostbite2_0.Frostbite;

namespace RimeLib.Mesh.Frostbite2_0
{
    public class MeshConverter : IMeshConverter
    {
        /// <summary>
        /// This class holds mesh data being read in and is stored in our own format so we can streamline the exporting process.
        /// Credits: Ma_rv, IceBloc
        /// </summary>
        public sealed class InternalMesh
        {
            public string Name = "";
            public bool IsSkinned;
            public List<Vertex> Vertices = new();
            public List<(int A, int B, int C)> Faces = new();

            public InternalMesh() { }
        }

        /// <summary>
        /// Stores vertex attributes for each element.
        /// Credits: Ma_rv, IceBloc
        /// </summary>
        public struct Vertex
        {
            public float PositionX;
            public float PositionY;
            public float PositionZ;
            public float NormalX;
            public float NormalY;
            public float NormalZ;
            public float TexCoordX;
            public float TexCoordY;
            public float BoneIndexA;
            public float BoneIndexB;
            public float BoneIndexC;
            public float BoneIndexD;
            public float BoneWeightA;
            public float BoneWeightB;
            public float BoneWeightC;
            public float BoneWeightD;
        }

        public void ConvertToBlender(IResourceObject p_Resource, IEngineMounter p_Mounter, RimeWriter p_Writer)
        {
            throw new NotImplementedException();
        }

        public void ConvertToGltf(IResourceObject p_Resource, IEngineMounter p_Mounter, RimeWriter p_Writer)
        {
            using var s_MeshReader = p_Resource.GetReader();
            var s_MeshData = s_MeshReader.ToArray();
            using var s_TempMeshReader = new RimeReader(new MemoryStream(s_MeshData));
            var s_MeshSetLayout = new MeshSetLayout(s_TempMeshReader);

            // Create a new GLTF model
            var s_Model = ModelRoot.CreateModel();
            s_Model.Asset.Generator = "Generated by RimeLib (c) 2020";
            s_Model.Asset.Copyright = "Exported by Rime (c) kiwidoggie productions 2017-2020, models copyright respective ip owners, not for redistribution";

            // Create a default scene
            var s_Scene = s_Model.UseScene("default");

            // Hold a new random for randomized colors
            var s_Random = new Random();

            // Iterate through each of the level of details objects
            for (var s_LodIndex = 0; s_LodIndex < s_MeshSetLayout.LodCount; ++s_LodIndex)
            {

                // Get the level of detail object
                var s_Lod = s_MeshSetLayout.Lods[s_LodIndex].Object;
                if (s_Lod == null)
                    throw new Exception("could not get lod");

                // Debug information
                var s_LodName = s_Lod.Name.Object;
                //if (!p_Options?.Quiet ?? false)
                //    Console.WriteLine($"Dumping rigid mesh ({s_LodName}) lod {s_LodIndex}");

                // Debug checking to make sure assumptions are correct
                if (s_Lod.CategorySubsetIndices.Length != (int)MeshSubsetCategory.MeshSubsetCategoryCount)
                    throw new Exception("category subset indicies don't match the count");

                // Get the data chunk
                var s_DataChunkId = s_Lod.DataChunkId;
                if (!p_Mounter.TryGetChunk(s_DataChunkId, out /*IMountedObject<IChunkVariant>*/ var p_Chunk))
                {
                    //if (!p_Options.Quiet)
                    //    Console.WriteLine($"could not find data: {BitConverter.ToString(s_DataChunkId.Id)}");

                    continue;
                }

                using var s_ChunkReader = p_Chunk.FirstVariant.GetReader();

                // Hold all of our data
                byte[] s_VertexChunkData = new byte[s_Lod.VertexDataSize];
                byte[] s_PrimitiveChunkData = new byte[s_Lod.IndexDataSize];
                byte[] s_ChunkData = s_ChunkReader.ReadBytes((int)s_ChunkReader.Length);

                // Read out all vertex and primitive chunk data
                using (var s_DataChunkReader = new RimeReader(new MemoryStream(s_ChunkData)))
                {
                    // Read out all vertitices
                    s_VertexChunkData = s_DataChunkReader.ReadBytes((int)s_Lod.VertexDataSize);

                    // Read out all of the primitive data
                    s_PrimitiveChunkData = s_DataChunkReader.ReadBytes((int)s_Lod.IndexDataSize);
                }

                var s_SubsetsDict = new Dictionary<MeshSubset, List<byte[]>>();

                var s_SubsetsList = new List<MeshSubset>();
                var s_VertexDataList = new List<byte[]>();
                var s_CurrentVertexCount = 0;
                var s_CurrentVertexSize = 0;

                // Parse out all of the verticies
                using (var s_VertexReader = new RimeReader(new MemoryStream(s_VertexChunkData)))
                {
                    var s_VertexBitmask = new bool[s_VertexChunkData.Length];

                    // Iterate through each of the subsets in the lod
                    for (var s_SubsetIndex = 0; s_SubsetIndex < s_Lod.Subsets.Count; ++s_SubsetIndex)
                    {
                        // Get the subset
                        var s_Subset = s_Lod.Subsets.Get[s_SubsetIndex];

                        // Get the vertex stride, this should be the same as the current stream (elements per vertex) size
                        var s_VertexStride = s_Subset.VertexStride;

                        s_VertexReader.Seek(s_Subset.VertexOffset, SeekOrigin.Begin);

                        // Hold a list for all of our vertex data
                        var s_Set = new List<byte[]>();

                        // Iterate through each of the verticies
                        for (var s_VertexIndex = 0; s_VertexIndex < s_Subset.VertexCount; ++s_VertexIndex)
                        {
                            for (var i = 0; i < s_VertexStride; ++i)
                                s_VertexBitmask[s_VertexReader.Position + i] = true;

                            // Read out the vertex information
                            var s_Bytes = s_VertexReader.ReadBytes(s_VertexStride);

                            // Add this array of bytes (of size vertex stride)
                            s_VertexDataList.Add(s_Bytes);
                            s_Set.Add(s_Bytes);

                            s_CurrentVertexCount++;
                            s_CurrentVertexSize += s_VertexStride;
                        }

                        s_SubsetsDict.Add(s_Subset, s_Set);
                        s_SubsetsList.Add(s_Subset);
                    }

                    var s_Any = s_VertexBitmask.Any(p_Bit => p_Bit == false);
                }

                // Hold the subset + parsed vertex information
                var s_ParsedSubsets = new Dictionary<MeshSubset, List<Dictionary<VertexElementUsage, dynamic>>>();

                // Iterate through each of the subsets + the raw data
                for (var s_SubsetIndex = 0; s_SubsetIndex < s_SubsetsDict.Count; s_SubsetIndex++)
                {
                    // Get the subset and data pair
                    var s_SubsetsPair = s_SubsetsDict.ElementAt(s_SubsetIndex);

                    var s_SubsetKey = s_SubsetsPair.Key;
                    var s_SubsetValue = s_SubsetsPair.Value;

                    // Get the geometry descriptor
                    var s_GeometryDesc = s_SubsetKey.GeometryDeclarationDesc;

                    // Iterate all vertices that are for this model
                    if (s_SubsetValue.Count != s_SubsetKey.VertexCount)
                        throw new Exception("vertex count does not match number of verts read");

                    // Parse all of the data
                    var s_VerticiesNiceList = new List<Dictionary<VertexElementUsage, dynamic>>();
                    for (var s_VertexIndex = 0; s_VertexIndex < s_SubsetValue.Count; ++s_VertexIndex)
                    {
                        var s_VertexData = s_SubsetValue[s_VertexIndex];

                        using var s_VertexReader = new RimeReader(new MemoryStream(s_VertexData));

                        var s_Dict = new Dictionary<VertexElementUsage, dynamic>();

                        foreach (var s_Element in s_GeometryDesc.Elements)
                        {
                            s_VertexReader.Seek(s_Element.Offset, SeekOrigin.Begin);

                            // Iterate each element and check the format and set to the usage
                            // There should not be more than one of the same kind of usage here
                            switch (s_Element.Format)
                            {
                                case VertexElementFormat.VertexElementFormat_None:
                                    break;
                                // Halfs
                                case VertexElementFormat.VertexElementFormat_Half:
                                    s_Dict[s_Element.Usage] = RimeMath.HalfToFloat(s_VertexReader.ReadUInt16());
                                    break;
                                case VertexElementFormat.VertexElementFormat_Half2:
                                    s_Dict[s_Element.Usage] = (RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()), RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()));
                                    break;
                                case VertexElementFormat.VertexElementFormat_Half3:
                                    s_Dict[s_Element.Usage] = (RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()), RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()), RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()));
                                    break;
                                case VertexElementFormat.VertexElementFormat_Half4:
                                    s_Dict[s_Element.Usage] = (RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()), RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()), RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()), RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()));
                                    break;

                                // Bytes
                                case VertexElementFormat.VertexElementFormat_UByteN:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadByte();
                                    break;
                                case VertexElementFormat.VertexElementFormat_Byte4: // Should be signed byte
                                case VertexElementFormat.VertexElementFormat_Byte4N:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadBytes(4);
                                    break;
                                case VertexElementFormat.VertexElementFormat_UByte4:
                                case VertexElementFormat.VertexElementFormat_UByte4N:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadBytes(4);
                                    break;

                                // Floats
                                case VertexElementFormat.VertexElementFormat_Float:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadSingle();
                                    break;
                                case VertexElementFormat.VertexElementFormat_Float2:
                                    s_Dict[s_Element.Usage] = (s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle());
                                    break;
                                case VertexElementFormat.VertexElementFormat_Float3:
                                    s_Dict[s_Element.Usage] = (s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle());
                                    break;
                                case VertexElementFormat.VertexElementFormat_Float4:
                                    s_Dict[s_Element.Usage] = (s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle());
                                    break;
                                default:
                                    Console.WriteLine($"Unknown Format usage {s_Element.Format}");
                                    throw new Exception($"Unknown format usage {s_Element.Format}");
                            }
                        }

                        s_VerticiesNiceList.Add(s_Dict);
                    }

                    // Verify that we have parsed all of the verticies
                    if (s_VerticiesNiceList.Count != s_SubsetKey.VertexCount)
                        throw new Exception("asdasdas");

                    // Add to the new map of subset + parsed vertitices
                    s_ParsedSubsets.Add(s_SubsetKey, s_VerticiesNiceList);
                }

                // Now order the mesh subset category + (subset + parsed vert data)
                var s_Categories = new Dictionary<MeshSubsetCategory, List<KeyValuePair<MeshSubset, List<Dictionary<VertexElementUsage, dynamic>>>>>();
                for (var s_CategoryIndex = 0; s_CategoryIndex < s_Lod.CategorySubsetIndices.Length; ++s_CategoryIndex)
                {
                    // Get the list of subsets per-category
                    var s_SubsetIndicies = s_Lod.CategorySubsetIndices[s_CategoryIndex].Get;

                    // Hold a list of subsets + parsed verts
                    var s_SubsetPairList = new List<KeyValuePair<MeshSubset, List<Dictionary<VertexElementUsage, dynamic>>>>();
                    foreach (var s_SubsetIndex in s_SubsetIndicies)
                    {
                        // Example: Opaque = 0x1, 0x2 (subset index)
                        var s_SubsetPair = s_ParsedSubsets.ElementAt(s_SubsetIndex);

                        s_SubsetPairList.Add(s_SubsetPair);
                    }

                    // Add to the dictionary for subset category, (subsets + vertex data)[]
                    s_Categories.Add((MeshSubsetCategory)s_CategoryIndex, s_SubsetPairList);
                }

                // We only want to get the opaque meshes, TODO: Iterate through everything
                var s_Ret = s_Categories[MeshSubsetCategory.MeshSubsetCategory_Opaque];

                // TODO: Hold list of subset + parsed verts + primitives

                // Open up a reader for our primitives
                using (var s_IndexReader = new RimeReader(new MemoryStream(s_PrimitiveChunkData)))
                {
                    // Iterate each subset pair
                    foreach (var s_SubsetPair in s_Ret)
                    {
                        // Get the subset
                        var s_SubsetKey = s_SubsetPair.Key;
                        var s_SubsetValue = s_SubsetPair.Value;

                        // Calculate the start offset in the index buffer
                        var s_SubsetStartIndex = s_SubsetKey.StartIndex;

                        // Validate the start offset
                        var s_SubsetStartOffset = Marshal.SizeOf<ushort>() * s_SubsetStartIndex;
                        if (s_SubsetStartOffset >= s_IndexReader.Length)
                            throw new Exception("subset start offset");

                        // Calculate and verify the end offset (that it's in-bounds)
                        var s_SubsetEndOffset = (Marshal.SizeOf<ushort>() * 3) * s_SubsetKey.PrimitiveCount; // * 3 for X, Y, Z
                        if (s_SubsetEndOffset > s_IndexReader.Length)
                            throw new Exception("subset end offset");

                        // Hold our index list
                        var s_PrimitiveList = new List<(ushort, ushort, ushort)>();
                        switch (s_SubsetKey.PrimitiveType)
                        {
                            // If we are parsing a triangle list, then read out the X, Y, Z indices
                            case RimeLib.Mesh.Frostbite.PrimitiveType.PrimitiveType_TriangleList:
                                s_IndexReader.Seek(s_SubsetStartOffset, SeekOrigin.Begin);
                                for (var s_PrimitiveIndex = 0; s_PrimitiveIndex < s_SubsetKey.PrimitiveCount; ++s_PrimitiveIndex)
                                    s_PrimitiveList.Add((s_IndexReader.ReadUInt16(), s_IndexReader.ReadUInt16(), s_IndexReader.ReadUInt16()));
                                break;
                            default:
                                throw new Exception("unimplemented primitive type");
                        }

                        // Continue with creating the gltf format
                        var s_RandomColor = new System.Numerics.Vector4((float)s_Random.NextDouble(), (float)s_Random.NextDouble(), (float)s_Random.NextDouble(), 1.0f);
#pragma warning disable CS0618 // Type or member is obsolete
                        var s_DebugMaterial = new MaterialBuilder(s_SubsetKey.MaterialName.Object ?? "")
                            .WithMetallicRoughnessShader().WithChannelParam(KnownChannel.BaseColor, s_RandomColor);
#pragma warning restore CS0618 // Type or member is obsolete

                        // Create a new GLTF mesh
                        var s_Mesh = new MeshBuilder<VertexPosition, VertexTexture1>($"{MeshSubsetCategory.MeshSubsetCategory_Opaque}_{s_Lod.ShortName.Object}");
                        var s_Primitive = s_Mesh.UsePrimitive(s_DebugMaterial);

                        // Iterate through all primitives
                        for (var s_PrimitiveIndex = 0; s_PrimitiveIndex < s_PrimitiveList.Count; ++s_PrimitiveIndex)
                        {
                            var s_PrimitiveIndices = s_PrimitiveList[s_PrimitiveIndex];

                            var s_FirstIndex = s_PrimitiveIndices.Item1;
                            if (s_FirstIndex > s_SubsetValue.Count)
                                throw new Exception("first index oob");

                            var s_FirstVertex = s_SubsetValue[s_FirstIndex];
                            if (!s_FirstVertex.TryGetValue(VertexElementUsage.VertexElementUsage_Pos, out dynamic? s_FirstVertexPos))
                                continue;


                            var s_SecondIndex = s_PrimitiveIndices.Item2;
                            if (s_SecondIndex > s_SubsetValue.Count)
                                throw new Exception("second index oob");

                            var s_SecondVertex = s_SubsetValue[s_SecondIndex];
                            if (!s_SecondVertex.TryGetValue(VertexElementUsage.VertexElementUsage_Pos, out dynamic? s_SecondVertexPos))
                                continue;

                            var s_ThirdIndex = s_PrimitiveIndices.Item3;
                            if (s_ThirdIndex > s_SubsetValue.Count)
                                throw new Exception("third index oob");

                            var s_ThirdVertex = s_SubsetValue[s_ThirdIndex];
                            if (!s_ThirdVertex.TryGetValue(VertexElementUsage.VertexElementUsage_Pos, out dynamic? s_ThirdVertexPos))
                                continue;


                            var s_FirstPosition = new VertexPosition(s_FirstVertexPos.Item1, s_FirstVertexPos.Item2, s_FirstVertexPos.Item3);
                            var s_SecondPosition = new VertexPosition(s_SecondVertexPos.Item1, s_SecondVertexPos.Item2, s_SecondVertexPos.Item3);
                            var s_ThirdPosition = new VertexPosition(s_ThirdVertexPos.Item1, s_ThirdVertexPos.Item2, s_ThirdVertexPos.Item3);


                            if (s_FirstVertex.TryGetValue(VertexElementUsage.VertexElementUsage_TexCoord0, out dynamic? s_FirstVertexTexture) &&
                                s_SecondVertex.TryGetValue(VertexElementUsage.VertexElementUsage_TexCoord0, out dynamic? s_SecondVertexTexture) &&
                                s_ThirdVertex.TryGetValue(VertexElementUsage.VertexElementUsage_TexCoord0, out dynamic? s_ThirdVertexTexture))
                            {
                                var s_FirstTexture = new VertexTexture1(new System.Numerics.Vector2(s_FirstVertexTexture.Item1, s_FirstVertexTexture.Item2));
                                var s_SecondTexture = new VertexTexture1(new System.Numerics.Vector2(s_SecondVertexTexture.Item1, s_SecondVertexTexture.Item2));
                                var s_ThirdTexture = new VertexTexture1(new System.Numerics.Vector2(s_ThirdVertexTexture.Item1, s_ThirdVertexTexture.Item2));

                                s_Primitive.AddTriangle((s_FirstPosition, s_FirstTexture), (s_SecondPosition, s_SecondTexture), (s_ThirdPosition, s_ThirdTexture));
                            }
                            else
                            {
                                //Console.WriteLine("No texcoords");
                                s_Primitive.AddTriangle(s_FirstPosition, s_SecondPosition, s_ThirdPosition);
                            }
                        }
                        //var s_BaseAddress = s_Lod.BoneShortNameArrayPartTransforms.BaseAddress;
                        // s_ChunkReader.Seek((long)s_BaseAddress, SeekOrigin.Begin);

                        //var l_MatrixTransform = new Matrix44(s_ChunkReader);

                        //var s_Transform = new RimeLib.Frostbite.Core.
                        //s_SceneBuilder.AddRigidMesh(s_Mesh, l_MatrixTransform.ToMatrix4x4());

                        s_Model.CreateMesh(s_Mesh);
                    }
                }

                foreach (var s_Mesh in s_Model.LogicalMeshes)
                    s_Model.UseScene("default").CreateNode().WithMesh(s_Mesh);

                //var s_ModelPath = Path.Join(p_Options?.OutputPath ?? "./", s_MeshSetLayout.Name.Object);
                //var s_ModelDirectory = Path.GetDirectoryName(s_ModelPath);

                //Directory.CreateDirectory(s_ModelDirectory);

                //s_Model.SaveGLTF(s_ModelPath, new WriteSettings() { JsonIndented = true });
                var s_Json = s_Model.GetJsonPreview();
                p_Writer.WriteLine(s_Json);
            }
        }

        public void ConvertToObj(IResourceObject p_Resource, IEngineMounter p_Mounter, RimeWriter p_Writer)
        {
            using var s_MeshReader = p_Resource.GetReader();
            var s_MeshData = s_MeshReader.ToArray();
            using var s_TempMeshReader = new RimeReader(new MemoryStream(s_MeshData));
            var s_MeshSet = new MeshSetLayout(s_TempMeshReader);

            var s_ConvertedMeshes = ConvertToInternal(s_MeshSet, p_Mounter);

            for (var l_MeshIndex = 0; l_MeshIndex < s_ConvertedMeshes.Count; ++l_MeshIndex)
                ExportOBJ(s_ConvertedMeshes.ElementAt(l_MeshIndex), p_Writer);
            
        }

        public void ConvertToText(IResourceObject p_Resource, IEngineMounter p_Mounter, RimeWriter p_Writer)
        {
            throw new NotImplementedException();
        }

        public EngineType[] GetSupportedEngines()
        {
            return new[] { EngineType.Frostbite2_0 };
        }


        internal static List<InternalMesh> ConvertToInternal(MeshSetLayout p_MeshSet, IEngineMounter p_Mounter)
        {
            List<InternalMesh> s_MeshList = new();

            // For each LOD.
            for (var i = 0; i < p_MeshSet.LodCount; i++)
            {
                var s_LodPtr = p_MeshSet.Lods[i];
                var s_Lod = s_LodPtr.Object;
                var s_LodChunkId = s_Lod.DataChunkId;

                if (!p_Mounter.TryGetChunk(s_LodChunkId, out var s_Chunk))
                    return new();

                using var s_TempLodReader = s_Chunk.FirstVariant.GetReader();
                var s_LodData = s_TempLodReader.ToArray();
                using var s_LodReader = new RimeReader(new MemoryStream(s_LodData));
                s_LodReader.Endianness = Endianness.LittleEndian;

                // For each MeshSubset.
                for (var l_SubsetIndex = 0; l_SubsetIndex < s_Lod.Subsets.Get.Length; l_SubsetIndex++)
                {
                    var l_Subset = s_Lod.Subsets.Get[l_SubsetIndex];
                    InternalMesh s_Mesh = new()
                    {
                        Name = l_Subset.MaterialName.Object + "_LOD" + i,
                        IsSkinned = false // TODO
                    };

                    var l_IndexStartOffset = s_Lod.VertexDataSize;

                    // Start reading vertices.
                    s_LodReader.Seek(l_Subset.VertexOffset, SeekOrigin.Begin);

                    for (int l_VertexIndex = 0; l_VertexIndex < l_Subset.VertexCount; l_VertexIndex++)
                    {
                        Vertex l_Vertex = new();

                        var l_PosElement = l_Subset.GeometryDeclarationDesc.GetByUsage(VertexElementUsage.VertexElementUsage_Pos);
                        if (l_PosElement is null)
                            throw new Exception("Geometry declaration descriptor position is missing.");

                        var l_NorElement =
                            l_Subset.GeometryDeclarationDesc.GetByUsage(VertexElementUsage.VertexElementUsage_Normal);
                        var l_UV0Element =
                            l_Subset.GeometryDeclarationDesc.GetByUsage(VertexElementUsage.VertexElementUsage_TexCoord0);

                        var l_Position = l_PosElement.Read(s_LodReader, l_Subset.VertexStride);
                        var l_Normals = l_NorElement == null
                            ? new Vector4()
                            : l_NorElement.Read(s_LodReader, l_Subset.VertexStride);
                        var texcoord = l_UV0Element == null
                            ? new Vector4()
                            : l_UV0Element.Read(s_LodReader, l_Subset.VertexStride);

                        // We're done reading the current vertex, move up the stream.
                        s_LodReader.Seek(l_Subset.VertexStride, SeekOrigin.Current);

                        l_Vertex.PositionX = l_Position.X;
                        l_Vertex.PositionY = l_Position.Y;
                        l_Vertex.PositionZ = l_Position.Z;
                        l_Vertex.NormalX = l_Normals.X;
                        l_Vertex.NormalY = l_Normals.Y;
                        l_Vertex.NormalZ = l_Normals.Z;
                        l_Vertex.TexCoordX = texcoord.X;
                        l_Vertex.TexCoordY = 1.0f - texcoord.Y;

                        s_Mesh.Vertices.Add(l_Vertex);
                    }

                    // Read face indices.
                    s_LodReader.Seek(l_IndexStartOffset + (l_Subset.StartIndex * 2), SeekOrigin.Begin);

                    for (int l_PrimitiveIndex = 0; l_PrimitiveIndex < l_Subset.PrimitiveCount; l_PrimitiveIndex++)
                    {
                        int l_FaceX = s_LodReader.ReadUInt16();
                        int l_FaceY = s_LodReader.ReadUInt16();
                        int l_FaceZ = s_LodReader.ReadUInt16();

                        s_Mesh.Faces.Add((l_FaceX, l_FaceY, l_FaceZ));
                    }

                    s_MeshList.Add(s_Mesh);
                }
            }

            return s_MeshList;
        }

        internal static void ExportOBJ(InternalMesh p_Mesh, RimeWriter p_Writer)
        {
            // using TextWriter s_Writer = new StreamWriter(File.OpenWrite($"{p_DestinationPath}.obj"));

            // Write object name.
            p_Writer.WriteLine($"o {p_Mesh.Name}");

            // Loop through each vertex.
            for (int i = 0; i < p_Mesh.Vertices.Count; i++)
            {
                // Write the position data.
                p_Writer.WriteLine($"v {p_Mesh.Vertices[i].PositionX} {p_Mesh.Vertices[i].PositionY} {p_Mesh.Vertices[i].PositionZ}");
                // Write the normal data.
                p_Writer.WriteLine($"vn {p_Mesh.Vertices[i].NormalX} {p_Mesh.Vertices[i].NormalY} {p_Mesh.Vertices[i].NormalZ}");
                // Write the UV data.
                p_Writer.WriteLine($"vt {p_Mesh.Vertices[i].TexCoordX} {p_Mesh.Vertices[i].TexCoordY}");
            }
            // Loop through each face index.
            for (int i = 0; i < p_Mesh.Faces.Count; i++)
            {
                // Get the current face (for readability).
                var f = p_Mesh.Faces[i];
                // Write three face indices (Format: pos/norm/uv).
                p_Writer.WriteLine($"f {f.A + 1}/{f.A + 1}/{f.A + 1} {f.B + 1}/{f.B + 1}/{f.B + 1} {f.C + 1}/{f.C + 1}/{f.C + 1}");
            }
        }
    }
}
