<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn />
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn />
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpGLTF.Core" Version="1.0.0-alpha0029" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.0-alpha0029" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
    <ProjectReference Include="..\RimeLib.Mesh\RimeLib.Mesh.csproj" />
  </ItemGroup>

</Project>
