<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Release;Debug</Configurations>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpGLTF.Core" Version="1.0.5" />
    <PackageReference Include="SharpGLTF.Runtime" Version="1.0.5" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
    <ProjectReference Include="..\RimeLib.Mesh\RimeLib.Mesh.csproj" />
  </ItemGroup>

</Project>
