<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Release;Debug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
	<ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
	<ProjectReference Include="..\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj" />
  </ItemGroup>

</Project>
