<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeLib.Serialization\RimeLib.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="fb\" />
  </ItemGroup>

</Project>
