<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>default</LangVersion>
    <Configurations>Release;Debug</Configurations>
    <RootNamespace>EbxExtractor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Content\RimeLib.Content.csproj" />
    <ProjectReference Include="..\..\RimeLib.Mesh\RimeLib.Mesh.csproj" />
    <ProjectReference Include="..\..\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Serialization\RimeLib.Serialization.csproj" />
    <ProjectReference Include="..\..\RimeLib.Shader.Frostbite2_0\RimeLib.Shader.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Texture.Frostbite2_0\RimeLib.Texture.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Texture\RimeLib.Texture.csproj" />
    <ProjectReference Include="..\..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
