<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RimeLib.Bindings.Frostbite2013_2.Battlefield4</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="fb\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RimeLib.Serialization\RimeLib.Serialization.csproj" />
    </ItemGroup>

</Project>
