<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
	<LangVersion>9.0</LangVersion>
	<Nullable>enable</Nullable>
	<OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
	<OutputType>Exe</OutputType>
	<Platforms>x64</Platforms>
</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Content\RimeLib.Content.csproj" />
    <ProjectReference Include="..\..\RimeLib.Shader.Frostbite2_0\RimeLib.Shader.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Shader\RimeLib.Shader.csproj" />
    <ProjectReference Include="..\..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
