<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Havok\RimeLib.Havok.csproj" />
    <ProjectReference Include="..\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj" />
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
