<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <VersionSuffix>1.0.0</VersionSuffix>
    <AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">0.0.0.1</AssemblyVersion>
    <AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
    <Version Condition=" '$(VersionSuffix)' == '' ">0.0.1.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.50.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.Metro" Version="4.50.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\Meta\Vec3Control.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\Meta\Vec2Control - Copy - Copy.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>Vec2Control - Copy.xaml.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\Meta\Vec2Control - Copy.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>Vec2Control.xaml.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Meta\Vec3Control.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
