<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.50.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.Metro" Version="4.50.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\Meta\Vec3Control.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\Meta\Vec2Control - Copy - Copy.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>Vec2Control - Copy.xaml.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\Meta\Vec2Control - Copy.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>Vec2Control.xaml.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Meta\Vec3Control.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
