<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Serialization\RimeLib.Serialization.csproj" />
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
