<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <!-- <EnableWindowsTargeting>true</EnableWindowsTargeting> -->
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
	    <UseWindowsForms>true</UseWindowsForms>
        <LangVersion>default</LangVersion>
        <Platforms>AnyCPU</Platforms>
        <Configurations>Release;Debug</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
      <PackageReference Include="Dirkster.AvalonDock.Themes.Metro" Version="4.72.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\External\GameTools.Net\GameToolsDotNet\GameToolsDotNet.csproj" />
      <ProjectReference Include="..\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj" />
      <ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
      <ProjectReference Include="..\RimeLib.Mesh.Frostbite2_0\RimeLib.Mesh.Frostbite2_0.csproj" />
      <ProjectReference Include="..\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj" />
      <ProjectReference Include="..\RimeLib.Shader.Frostbite2_0\RimeLib.Shader.Frostbite2_0.csproj" />
      <ProjectReference Include="..\RimeLib.Terrain.Frostbite2_0\RimeLib.Terrain.Frostbite2_0.csproj" />
      <ProjectReference Include="..\RimeLib.Texture.Frostbite2_0\RimeLib.Texture.Frostbite2_0.csproj" />
      <ProjectReference Include="..\RimeLib.Texture\RimeLib.Texture.csproj" />
      <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="ImGui.NET">
        <HintPath>..\External\GameTools.Net\ImGui.NET.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="Rendering\Shaders\Deferred.hlsl">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>