<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.6.0" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.0-alpha0015" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj" />
    <ProjectReference Include="..\..\RimeLib.Content\RimeLib.Content.csproj" />
    <ProjectReference Include="..\..\RimeLib.Mesh\RimeLib.Mesh.csproj" />
    <ProjectReference Include="..\..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
