using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.Serialization;
using System.Security.Cryptography;
using System.Text;
using RimeLib.IO;

namespace RimeLib.Frostbite.Core
{
    /// <summary>
    /// fb::ResourceRef implementation
    /// </summary>
    [Serializable]
    public class ResourceRef : IFbSerializable, ISerializable
    {
        /// <summary>
        /// Internal structure
        /// iirc resourcerefs are generated by
        /// 1. take lower path name and add it to buffer
        /// 2. take data and add it to buffer
        /// 3. md5 data
        /// 4. xor both uint64 parts of hash together
        /// 5. set bit 1 to make it non ptr/data ref (resourcerefs are replaced by pointers at runtime.)
        /// </summary>
        public ulong Id { get; set; }

        public bool IsRef => (Id & 1) != 0;
        public bool IsPtr => (Id & 1) == 0;
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public ResourceRef()
        {

        }

        /// <summary>
        /// Construct from a opened RimeReader
        /// </summary>
        /// <param name="p_Reader">Reader opened to the position of the ResourceRef</param>
        public ResourceRef(RimeReader p_Reader)
        {
            Deserialize(p_Reader);
        }

        /// <summary>
        /// Constructor from Id
        /// </summary>
        /// <param name="p_Id">Id</param>
        public ResourceRef(ulong p_Id)
        {
            Id = p_Id;
        }

        public ResourceRef(string p_Name, IReadableObject p_Data)
        {
            Id = GenerateId(p_Name, p_Data);
        }

        /// <summary>
        /// TODO: Documentation
        /// </summary>
        /// <param name="p_Info"></param>
        /// <param name="p_Context"></param>
        protected ResourceRef(SerializationInfo p_Info, StreamingContext p_Context)
        {
            throw new NotImplementedException();
        }
        //public static implicit operator ResourceRef(ulong p_Elem) => new(p_Elem);
        public static implicit operator ResourceRef(long p_Elem) => new((ulong)p_Elem);
        public static implicit operator ulong(ResourceRef p_Elem) => p_Elem.Id;

        /// <summary>
        /// Produces string representation of id in hex
        /// </summary>
        /// <returns>String of id in hex string</returns>
        public override string ToString()
        {
            return Id.ToString("X");
        }

        /// <summary>
        /// ToString with provided format
        /// </summary>
        /// <param name="p_Format">Format to produce the id (uint64)</param>
        /// <returns>String of id</returns>
        public string ToString(string p_Format)
        {
            return Id.ToString(p_Format);
        }

        /// <summary>
        /// TODO: Documentation
        /// </summary>
        /// <param name="p_Id"></param>
        public static implicit operator ResourceRef(ulong p_Id)
        {
            return new ResourceRef(p_Id);
        }

        /// <summary>
        /// Equals operator
        /// </summary>
        /// <param name="p_First">First</param>
        /// <param name="p_Second">Second</param>
        /// <returns>True if equal, false otherwise</returns>
        public static bool operator ==(ResourceRef? p_First, ResourceRef? p_Second)
        {
            if (ReferenceEquals(p_First, p_Second))
                return true;

            if (p_First is null || p_Second is null)
                return false;

            return p_First.Id == p_Second.Id;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="p_Left"></param>
        /// <param name="p_Right"></param>
        /// <returns></returns>
        public static bool operator !=(ResourceRef? p_Left, ResourceRef? p_Right)
        {
            if (ReferenceEquals(p_Left, p_Right))
                return false;

            if (p_Left is null || p_Right is null)
                return true;

            return p_Left.Id != p_Right.Id;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="p_Obj"></param>
        /// <returns></returns>
        public override bool Equals(object? p_Obj)
        {
            if (ReferenceEquals(null, p_Obj))
                return false;

            if (ReferenceEquals(this, p_Obj))
                return true;

            if (p_Obj is ResourceRef s_Ref)
                return s_Ref == this;

            return false;
        }

        /// <summary>
        /// Gets the hash code of the Id
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="p_Info"></param>
        /// <param name="p_Context"></param>
        public virtual void GetObjectData(SerializationInfo p_Info, StreamingContext p_Context)
        {
            p_Info.AddValue("fb::ResourceRef", ToString(), typeof(string));
        }

        /// <summary>
        /// Writes this ResourceRef to an opened writer
        /// </summary>
        /// <param name="p_Writer">Writer opened to the position where the ResourceRef is going</param>
        /// <returns>True always</returns>
        public bool Serialize(RimeWriter p_Writer)
        {
            p_Writer.Write(Id);
            return true;
        }

        /// <summary>
        /// Serializes to a byte array
        /// </summary>
        /// <returns>Bytes of the id</returns>
        public bool Serialize([NotNullWhen(true)] out byte[]? p_Data)
        {
            p_Data = null;

            using (var s_Writer = new RimeWriter(new MemoryStream()))
            {
                if (!Serialize(s_Writer))
                    return false;

                s_Writer.Flush();
                p_Data = ((MemoryStream) s_Writer.BaseStream).ToArray();
            }

            return true;
        }

        public void Deserialize(RimeReader p_Reader)
        {
            Id = p_Reader.ReadUInt64();
        }

        public void Deserialize(byte[] p_Data)
        {
            throw new NotImplementedException();
        }

        private static ResourceRef GenerateId(string p_Name, IReadableObject p_Data)
        {
            // HOW TO: lowercase path of the resource, 
            // prepend it to the resource data, 
            // get the md5 hash of that, 
            // split it in two 64-bit little-endian integers, 
            // and XOR them
            // OR that result with 1.

            // TODO: This is AI slop. Test if this works.
            using var s_Md5 = MD5.Create();
            var s_Path = p_Name.ToLower();
            var s_PathBytes = Encoding.ASCII.GetBytes(s_Path);

            using (var s_Reader = p_Data.GetReader())
            {
                var s_ResourceData = new byte[p_Data.GetSize()];
                s_Reader.Read(s_ResourceData, 0, s_ResourceData.Length);

                var s_CombinedData = new byte[s_PathBytes.Length + s_ResourceData.Length];
                Buffer.BlockCopy(s_PathBytes, 0, s_CombinedData, 0, s_PathBytes.Length);
                Buffer.BlockCopy(s_ResourceData, 0, s_CombinedData, s_PathBytes.Length, s_ResourceData.Length);

                var s_Hash = s_Md5.ComputeHash(s_CombinedData);

                var s_Low = BitConverter.ToUInt64(s_Hash, 0);
                var s_High = BitConverter.ToUInt64(s_Hash, 8);

                var s_Id = (s_Low ^ s_High) | 1;
                return s_Id;
            }
        }
    }
}
