<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
	<LangVersion>9.0</LangVersion>
	<Nullable>enable</Nullable>
	<OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<Platforms>x64</Platforms>
</PropertyGroup>

  <ItemGroup>
    <Folder Include="Frostbite\Solutions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj" />
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
