<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>default</LangVersion>
        <Nullable>enable</Nullable>
        <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Platforms>AnyCPU</Platforms>
        <Configurations>Release;Debug</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Frostbite\Solutions\" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\RimeLib.Mesh\RimeLib.Mesh.csproj" />
        <ProjectReference Include="..\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj" />
        <ProjectReference Include="..\RimeLib.Texture.Frostbite2_0\RimeLib.Texture.Frostbite2_0.csproj" />
        <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.5.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
