<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>default</LangVersion>
		<Nullable>enable</Nullable>
		<OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<Platforms>AnyCPU</Platforms>
		<Configurations>Release;Debug</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RimeLib.Texture\RimeLib.Texture.csproj" />
		<ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
	</ItemGroup>

</Project>
