<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net5.0</TargetFramework>
		<Platforms>x64</Platforms>
		<ApplicationIcon />
		<Nullable>enable</Nullable>
		<OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
		<StartupObject />
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLib.Texture\RimeLib.Texture.csproj" />
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
