<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Release;Debug</Configurations>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
