<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Release;Debug</Configurations>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <OutputPath>$(SolutionDir)/bin/$(Configuration)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\RimeLib.Content\RimeLib.Content.csproj" />
	  <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

</Project>
