//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FBC.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFBCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class FBCBaseListener : IFBCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.fbc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFbc([NotNull] FBCParser.FbcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.fbc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFbc([NotNull] FBCParser.FbcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessModifier([NotNull] FBCParser.AccessModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessModifier([NotNull] FBCParser.AccessModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.memberType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberType([NotNull] FBCParser.MemberTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.memberType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberType([NotNull] FBCParser.MemberTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerType([NotNull] FBCParser.IntegerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerType([NotNull] FBCParser.IntegerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.fileInclude"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileInclude([NotNull] FBCParser.FileIncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.fileInclude"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileInclude([NotNull] FBCParser.FileIncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.includeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeBlock([NotNull] FBCParser.IncludeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.includeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeBlock([NotNull] FBCParser.IncludeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.namespaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceBlock([NotNull] FBCParser.NamespaceBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.namespaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceBlock([NotNull] FBCParser.NamespaceBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.@namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace([NotNull] FBCParser.NamespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.@namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace([NotNull] FBCParser.NamespaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.namespaceString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceString([NotNull] FBCParser.NamespaceStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.namespaceString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceString([NotNull] FBCParser.NamespaceStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] FBCParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] FBCParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.attributeParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeParam([NotNull] FBCParser.AttributeParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.attributeParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeParam([NotNull] FBCParser.AttributeParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] FBCParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] FBCParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.attributeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeBlock([NotNull] FBCParser.AttributeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.attributeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeBlock([NotNull] FBCParser.AttributeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeContents([NotNull] FBCParser.TypeContentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeContents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeContents([NotNull] FBCParser.TypeContentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.arrayModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayModifier([NotNull] FBCParser.ArrayModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.arrayModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayModifier([NotNull] FBCParser.ArrayModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeMember([NotNull] FBCParser.TypeMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeMember([NotNull] FBCParser.TypeMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeEvent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeEvent([NotNull] FBCParser.TypeEventContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeEvent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeEvent([NotNull] FBCParser.TypeEventContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeNativeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNativeFunction([NotNull] FBCParser.TypeNativeFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeNativeFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNativeFunction([NotNull] FBCParser.TypeNativeFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeManagedFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeManagedFunction([NotNull] FBCParser.TypeManagedFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeManagedFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeManagedFunction([NotNull] FBCParser.TypeManagedFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.blockBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockBody([NotNull] FBCParser.BlockBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.blockBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockBody([NotNull] FBCParser.BlockBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.classBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBlock([NotNull] FBCParser.ClassBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.classBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBlock([NotNull] FBCParser.ClassBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.classInheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInheritance([NotNull] FBCParser.ClassInheritanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.classInheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInheritance([NotNull] FBCParser.ClassInheritanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.structBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructBlock([NotNull] FBCParser.StructBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.structBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructBlock([NotNull] FBCParser.StructBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBlock([NotNull] FBCParser.EnumBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBlock([NotNull] FBCParser.EnumBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDataType([NotNull] FBCParser.EnumDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDataType([NotNull] FBCParser.EnumDataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBody([NotNull] FBCParser.EnumBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBody([NotNull] FBCParser.EnumBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] FBCParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] FBCParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumLastMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumLastMember([NotNull] FBCParser.EnumLastMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumLastMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumLastMember([NotNull] FBCParser.EnumLastMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumMemberValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumMemberValue([NotNull] FBCParser.EnumMemberValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumMemberValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumMemberValue([NotNull] FBCParser.EnumMemberValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumTerminator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumTerminator([NotNull] FBCParser.EnumTerminatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumTerminator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumTerminator([NotNull] FBCParser.EnumTerminatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeAlignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeAlignment([NotNull] FBCParser.TypeAlignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeAlignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeAlignment([NotNull] FBCParser.TypeAlignmentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
