//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FBC.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FBCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IFBCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.fbc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFbc([NotNull] FBCParser.FbcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.fbc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFbc([NotNull] FBCParser.FbcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessModifier([NotNull] FBCParser.AccessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessModifier([NotNull] FBCParser.AccessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.memberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberType([NotNull] FBCParser.MemberTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.memberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberType([NotNull] FBCParser.MemberTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerType([NotNull] FBCParser.IntegerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerType([NotNull] FBCParser.IntegerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.fileInclude"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileInclude([NotNull] FBCParser.FileIncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.fileInclude"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileInclude([NotNull] FBCParser.FileIncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.includeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeBlock([NotNull] FBCParser.IncludeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.includeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeBlock([NotNull] FBCParser.IncludeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.namespaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceBlock([NotNull] FBCParser.NamespaceBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.namespaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceBlock([NotNull] FBCParser.NamespaceBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespace([NotNull] FBCParser.NamespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespace([NotNull] FBCParser.NamespaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.namespaceString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceString([NotNull] FBCParser.NamespaceStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.namespaceString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceString([NotNull] FBCParser.NamespaceStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] FBCParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] FBCParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.attributeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeParam([NotNull] FBCParser.AttributeParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.attributeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeParam([NotNull] FBCParser.AttributeParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] FBCParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] FBCParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.attributeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeBlock([NotNull] FBCParser.AttributeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.attributeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeBlock([NotNull] FBCParser.AttributeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeContents([NotNull] FBCParser.TypeContentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeContents([NotNull] FBCParser.TypeContentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.arrayModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayModifier([NotNull] FBCParser.ArrayModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.arrayModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayModifier([NotNull] FBCParser.ArrayModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeMember([NotNull] FBCParser.TypeMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeMember([NotNull] FBCParser.TypeMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeEvent([NotNull] FBCParser.TypeEventContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeEvent([NotNull] FBCParser.TypeEventContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeNativeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNativeFunction([NotNull] FBCParser.TypeNativeFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeNativeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNativeFunction([NotNull] FBCParser.TypeNativeFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeManagedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeManagedFunction([NotNull] FBCParser.TypeManagedFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeManagedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeManagedFunction([NotNull] FBCParser.TypeManagedFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.blockBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockBody([NotNull] FBCParser.BlockBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.blockBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockBody([NotNull] FBCParser.BlockBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.classBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBlock([NotNull] FBCParser.ClassBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.classBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBlock([NotNull] FBCParser.ClassBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.classInheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassInheritance([NotNull] FBCParser.ClassInheritanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.classInheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassInheritance([NotNull] FBCParser.ClassInheritanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.structBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructBlock([NotNull] FBCParser.StructBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.structBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructBlock([NotNull] FBCParser.StructBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBlock([NotNull] FBCParser.EnumBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBlock([NotNull] FBCParser.EnumBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDataType([NotNull] FBCParser.EnumDataTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDataType([NotNull] FBCParser.EnumDataTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] FBCParser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] FBCParser.EnumBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValue([NotNull] FBCParser.EnumValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValue([NotNull] FBCParser.EnumValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumLastMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumLastMember([NotNull] FBCParser.EnumLastMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumLastMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumLastMember([NotNull] FBCParser.EnumLastMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumMemberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumMemberValue([NotNull] FBCParser.EnumMemberValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumMemberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumMemberValue([NotNull] FBCParser.EnumMemberValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.enumTerminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumTerminator([NotNull] FBCParser.EnumTerminatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.enumTerminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumTerminator([NotNull] FBCParser.EnumTerminatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBCParser.typeAlignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAlignment([NotNull] FBCParser.TypeAlignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBCParser.typeAlignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAlignment([NotNull] FBCParser.TypeAlignmentContext context);
}
