//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FBC.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class FBCParser : Parser {
	public const int
		PUBLIC=1, PRIVATE=2, PROTECTED=3, FLOAT=4, DOUBLE=5, INT64=6, UINT64=7, 
		INT32=8, UINT32=9, INT16=10, UINT16=11, INT8=12, UINT8=13, BOOL=14, STRING=15, 
		GUID=16, SHA1=17, TRUE=18, FALSE=19, CLASS_MEMBER=20, ENUM_MEMBER=21, 
		STRUCT_MEMBER=22, ARRAY=23, LBRACKET=24, RBRACKET=25, LBRACE=26, RBRACE=27, 
		LPAREN=28, RPAREN=29, NATIVE_START=30, MANAGED_START=31, BLOCK_END=32, 
		NAMESPACE=33, CLASS=34, ENUM=35, STRUCT=36, EVENT=37, INCLUDE=38, ALIGN=39, 
		DOT=40, COMMA=41, COLON=42, SEMICOLON=43, DOUBLECOLON=44, EQUALS=45, DASH=46, 
		IDENTIFIER=47, FLOAT_NUMBER=48, INTEGER=49, SINGLE_LINE_COMMENT=50, DELIMITED_COMMENT=51, 
		WHITESPACE=52, ANGLE_STRING=53, QUOTED_STRING=54, WS=55;
	public const int
		RULE_fbc = 0, RULE_accessModifier = 1, RULE_memberType = 2, RULE_integerType = 3, 
		RULE_fileInclude = 4, RULE_includeBlock = 5, RULE_namespaceBlock = 6, 
		RULE_namespace = 7, RULE_namespaceString = 8, RULE_definition = 9, RULE_attributeParam = 10, 
		RULE_attribute = 11, RULE_attributeBlock = 12, RULE_typeContents = 13, 
		RULE_arrayModifier = 14, RULE_typeMember = 15, RULE_typeEvent = 16, RULE_typeNativeFunction = 17, 
		RULE_typeManagedFunction = 18, RULE_blockBody = 19, RULE_classBlock = 20, 
		RULE_classInheritance = 21, RULE_structBlock = 22, RULE_enumBlock = 23, 
		RULE_enumDataType = 24, RULE_enumBody = 25, RULE_enumValue = 26, RULE_enumLastMember = 27, 
		RULE_enumMemberValue = 28, RULE_enumTerminator = 29, RULE_typeAlignment = 30;
	public static readonly string[] ruleNames = {
		"fbc", "accessModifier", "memberType", "integerType", "fileInclude", "includeBlock", 
		"namespaceBlock", "namespace", "namespaceString", "definition", "attributeParam", 
		"attribute", "attributeBlock", "typeContents", "arrayModifier", "typeMember", 
		"typeEvent", "typeNativeFunction", "typeManagedFunction", "blockBody", 
		"classBlock", "classInheritance", "structBlock", "enumBlock", "enumDataType", 
		"enumBody", "enumValue", "enumLastMember", "enumMemberValue", "enumTerminator", 
		"typeAlignment"
	};

	private static readonly string[] _LiteralNames = {
		null, "'public'", "'private'", "'protected'", "'float'", "'double'", "'int64'", 
		"'uint64'", "'int32'", "'uint32'", "'int16'", "'uint16'", "'int8'", "'uint8'", 
		"'bool'", "'string'", "'guid'", "'sha1'", "'true'", "'false'", "'class_member'", 
		"'enum_member'", "'struct_member'", "'array'", "'['", "']'", "'{'", "'}'", 
		"'('", "')'", "'/#N'", "'/#M'", "'#/'", "'namespace'", "'class'", "'enum'", 
		"'struct'", "'event'", "'#include'", "'align'", "'.'", "','", "':'", "';'", 
		"'::'", "'='", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PUBLIC", "PRIVATE", "PROTECTED", "FLOAT", "DOUBLE", "INT64", "UINT64", 
		"INT32", "UINT32", "INT16", "UINT16", "INT8", "UINT8", "BOOL", "STRING", 
		"GUID", "SHA1", "TRUE", "FALSE", "CLASS_MEMBER", "ENUM_MEMBER", "STRUCT_MEMBER", 
		"ARRAY", "LBRACKET", "RBRACKET", "LBRACE", "RBRACE", "LPAREN", "RPAREN", 
		"NATIVE_START", "MANAGED_START", "BLOCK_END", "NAMESPACE", "CLASS", "ENUM", 
		"STRUCT", "EVENT", "INCLUDE", "ALIGN", "DOT", "COMMA", "COLON", "SEMICOLON", 
		"DOUBLECOLON", "EQUALS", "DASH", "IDENTIFIER", "FLOAT_NUMBER", "INTEGER", 
		"SINGLE_LINE_COMMENT", "DELIMITED_COMMENT", "WHITESPACE", "ANGLE_STRING", 
		"QUOTED_STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FBC.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public FBCParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this,_ATN);
	}
	public partial class FbcContext : ParserRuleContext {
		public IncludeBlockContext includeBlock() {
			return GetRuleContext<IncludeBlockContext>(0);
		}
		public NamespaceBlockContext namespaceBlock() {
			return GetRuleContext<NamespaceBlockContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(FBCParser.Eof, 0); }
		public DefinitionContext[] definition() {
			return GetRuleContexts<DefinitionContext>();
		}
		public DefinitionContext definition(int i) {
			return GetRuleContext<DefinitionContext>(i);
		}
		public FbcContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fbc; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterFbc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitFbc(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFbc(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FbcContext fbc() {
		FbcContext _localctx = new FbcContext(Context, State);
		EnterRule(_localctx, 0, RULE_fbc);
		int _la;
		try {
			State = 75;
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 62; includeBlock();
				State = 63; namespaceBlock();
				State = 64; Match(Eof);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 66; includeBlock();
				{
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LBRACKET) | (1L << CLASS) | (1L << ENUM) | (1L << STRUCT) | (1L << SINGLE_LINE_COMMENT) | (1L << DELIMITED_COMMENT))) != 0)) {
					{
					{
					State = 67; definition();
					}
					}
					State = 72;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				}
				State = 73; Match(Eof);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AccessModifierContext : ParserRuleContext {
		public ITerminalNode PUBLIC() { return GetToken(FBCParser.PUBLIC, 0); }
		public ITerminalNode PRIVATE() { return GetToken(FBCParser.PRIVATE, 0); }
		public ITerminalNode PROTECTED() { return GetToken(FBCParser.PROTECTED, 0); }
		public AccessModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_accessModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterAccessModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitAccessModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAccessModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AccessModifierContext accessModifier() {
		AccessModifierContext _localctx = new AccessModifierContext(Context, State);
		EnterRule(_localctx, 2, RULE_accessModifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			_la = TokenStream.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PUBLIC) | (1L << PRIVATE) | (1L << PROTECTED))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemberTypeContext : ParserRuleContext {
		public ITerminalNode FLOAT() { return GetToken(FBCParser.FLOAT, 0); }
		public ITerminalNode DOUBLE() { return GetToken(FBCParser.DOUBLE, 0); }
		public ITerminalNode BOOL() { return GetToken(FBCParser.BOOL, 0); }
		public ITerminalNode STRING() { return GetToken(FBCParser.STRING, 0); }
		public ITerminalNode GUID() { return GetToken(FBCParser.GUID, 0); }
		public ITerminalNode SHA1() { return GetToken(FBCParser.SHA1, 0); }
		public ITerminalNode INT64() { return GetToken(FBCParser.INT64, 0); }
		public ITerminalNode UINT64() { return GetToken(FBCParser.UINT64, 0); }
		public ITerminalNode INT32() { return GetToken(FBCParser.INT32, 0); }
		public ITerminalNode UINT32() { return GetToken(FBCParser.UINT32, 0); }
		public ITerminalNode INT16() { return GetToken(FBCParser.INT16, 0); }
		public ITerminalNode UINT16() { return GetToken(FBCParser.UINT16, 0); }
		public ITerminalNode INT8() { return GetToken(FBCParser.INT8, 0); }
		public ITerminalNode UINT8() { return GetToken(FBCParser.UINT8, 0); }
		public NamespaceStringContext namespaceString() {
			return GetRuleContext<NamespaceStringContext>(0);
		}
		public MemberTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_memberType; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterMemberType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitMemberType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMemberType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MemberTypeContext memberType() {
		MemberTypeContext _localctx = new MemberTypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_memberType);
		try {
			State = 94;
			switch (TokenStream.La(1)) {
			case FLOAT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 79; Match(FLOAT);
				}
				break;
			case DOUBLE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 80; Match(DOUBLE);
				}
				break;
			case BOOL:
				EnterOuterAlt(_localctx, 3);
				{
				State = 81; Match(BOOL);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 4);
				{
				State = 82; Match(STRING);
				}
				break;
			case GUID:
				EnterOuterAlt(_localctx, 5);
				{
				State = 83; Match(GUID);
				}
				break;
			case SHA1:
				EnterOuterAlt(_localctx, 6);
				{
				State = 84; Match(SHA1);
				}
				break;
			case INT64:
				EnterOuterAlt(_localctx, 7);
				{
				State = 85; Match(INT64);
				}
				break;
			case UINT64:
				EnterOuterAlt(_localctx, 8);
				{
				State = 86; Match(UINT64);
				}
				break;
			case INT32:
				EnterOuterAlt(_localctx, 9);
				{
				State = 87; Match(INT32);
				}
				break;
			case UINT32:
				EnterOuterAlt(_localctx, 10);
				{
				State = 88; Match(UINT32);
				}
				break;
			case INT16:
				EnterOuterAlt(_localctx, 11);
				{
				State = 89; Match(INT16);
				}
				break;
			case UINT16:
				EnterOuterAlt(_localctx, 12);
				{
				State = 90; Match(UINT16);
				}
				break;
			case INT8:
				EnterOuterAlt(_localctx, 13);
				{
				State = 91; Match(INT8);
				}
				break;
			case UINT8:
				EnterOuterAlt(_localctx, 14);
				{
				State = 92; Match(UINT8);
				}
				break;
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 15);
				{
				State = 93; namespaceString();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntegerTypeContext : ParserRuleContext {
		public ITerminalNode INT64() { return GetToken(FBCParser.INT64, 0); }
		public ITerminalNode UINT64() { return GetToken(FBCParser.UINT64, 0); }
		public ITerminalNode INT32() { return GetToken(FBCParser.INT32, 0); }
		public ITerminalNode UINT32() { return GetToken(FBCParser.UINT32, 0); }
		public ITerminalNode INT16() { return GetToken(FBCParser.INT16, 0); }
		public ITerminalNode UINT16() { return GetToken(FBCParser.UINT16, 0); }
		public ITerminalNode INT8() { return GetToken(FBCParser.INT8, 0); }
		public ITerminalNode UINT8() { return GetToken(FBCParser.UINT8, 0); }
		public IntegerTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_integerType; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterIntegerType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitIntegerType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntegerType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntegerTypeContext integerType() {
		IntegerTypeContext _localctx = new IntegerTypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_integerType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			_la = TokenStream.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT64) | (1L << UINT64) | (1L << INT32) | (1L << UINT32) | (1L << INT16) | (1L << UINT16) | (1L << INT8) | (1L << UINT8))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FileIncludeContext : ParserRuleContext {
		public ITerminalNode INCLUDE() { return GetToken(FBCParser.INCLUDE, 0); }
		public ITerminalNode ANGLE_STRING() { return GetToken(FBCParser.ANGLE_STRING, 0); }
		public FileIncludeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fileInclude; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterFileInclude(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitFileInclude(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFileInclude(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileIncludeContext fileInclude() {
		FileIncludeContext _localctx = new FileIncludeContext(Context, State);
		EnterRule(_localctx, 8, RULE_fileInclude);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98; Match(INCLUDE);
			State = 99; Match(ANGLE_STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IncludeBlockContext : ParserRuleContext {
		public FileIncludeContext[] fileInclude() {
			return GetRuleContexts<FileIncludeContext>();
		}
		public FileIncludeContext fileInclude(int i) {
			return GetRuleContext<FileIncludeContext>(i);
		}
		public ITerminalNode SINGLE_LINE_COMMENT() { return GetToken(FBCParser.SINGLE_LINE_COMMENT, 0); }
		public ITerminalNode DELIMITED_COMMENT() { return GetToken(FBCParser.DELIMITED_COMMENT, 0); }
		public IncludeBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_includeBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterIncludeBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitIncludeBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncludeBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IncludeBlockContext includeBlock() {
		IncludeBlockContext _localctx = new IncludeBlockContext(Context, State);
		EnterRule(_localctx, 10, RULE_includeBlock);
		int _la;
		try {
			State = 110;
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 105;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==INCLUDE) {
					{
					{
					State = 102; fileInclude();
					}
					}
					State = 107;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 108; Match(SINGLE_LINE_COMMENT);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 109; Match(DELIMITED_COMMENT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceBlockContext : ParserRuleContext {
		public NamespaceContext @namespace() {
			return GetRuleContext<NamespaceContext>(0);
		}
		public DefinitionContext[] definition() {
			return GetRuleContexts<DefinitionContext>();
		}
		public DefinitionContext definition(int i) {
			return GetRuleContext<DefinitionContext>(i);
		}
		public ITerminalNode SINGLE_LINE_COMMENT() { return GetToken(FBCParser.SINGLE_LINE_COMMENT, 0); }
		public ITerminalNode DELIMITED_COMMENT() { return GetToken(FBCParser.DELIMITED_COMMENT, 0); }
		public NamespaceBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespaceBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterNamespaceBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitNamespaceBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespaceBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceBlockContext namespaceBlock() {
		NamespaceBlockContext _localctx = new NamespaceBlockContext(Context, State);
		EnterRule(_localctx, 12, RULE_namespaceBlock);
		int _la;
		try {
			State = 121;
			switch (TokenStream.La(1)) {
			case NAMESPACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 112; @namespace();
				{
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LBRACKET) | (1L << CLASS) | (1L << ENUM) | (1L << STRUCT) | (1L << SINGLE_LINE_COMMENT) | (1L << DELIMITED_COMMENT))) != 0)) {
					{
					{
					State = 113; definition();
					}
					}
					State = 118;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				}
				}
				break;
			case SINGLE_LINE_COMMENT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 119; Match(SINGLE_LINE_COMMENT);
				}
				break;
			case DELIMITED_COMMENT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 120; Match(DELIMITED_COMMENT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceContext : ParserRuleContext {
		public ITerminalNode NAMESPACE() { return GetToken(FBCParser.NAMESPACE, 0); }
		public NamespaceStringContext namespaceString() {
			return GetRuleContext<NamespaceStringContext>(0);
		}
		public ITerminalNode SEMICOLON() { return GetToken(FBCParser.SEMICOLON, 0); }
		public NamespaceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterNamespace(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitNamespace(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespace(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceContext @namespace() {
		NamespaceContext _localctx = new NamespaceContext(Context, State);
		EnterRule(_localctx, 14, RULE_namespace);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123; Match(NAMESPACE);
			State = 124; namespaceString();
			State = 125; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceStringContext : ParserRuleContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(FBCParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(FBCParser.IDENTIFIER, i);
		}
		public ITerminalNode[] DOUBLECOLON() { return GetTokens(FBCParser.DOUBLECOLON); }
		public ITerminalNode DOUBLECOLON(int i) {
			return GetToken(FBCParser.DOUBLECOLON, i);
		}
		public NamespaceStringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespaceString; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterNamespaceString(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitNamespaceString(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespaceString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceStringContext namespaceString() {
		NamespaceStringContext _localctx = new NamespaceStringContext(Context, State);
		EnterRule(_localctx, 16, RULE_namespaceString);
		int _la;
		try {
			State = 136;
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 127; Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 128; Match(IDENTIFIER);
				State = 133;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==DOUBLECOLON) {
					{
					{
					State = 129; Match(DOUBLECOLON);
					State = 130; Match(IDENTIFIER);
					}
					}
					State = 135;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinitionContext : ParserRuleContext {
		public ClassBlockContext classBlock() {
			return GetRuleContext<ClassBlockContext>(0);
		}
		public StructBlockContext structBlock() {
			return GetRuleContext<StructBlockContext>(0);
		}
		public EnumBlockContext enumBlock() {
			return GetRuleContext<EnumBlockContext>(0);
		}
		public ITerminalNode SINGLE_LINE_COMMENT() { return GetToken(FBCParser.SINGLE_LINE_COMMENT, 0); }
		public ITerminalNode DELIMITED_COMMENT() { return GetToken(FBCParser.DELIMITED_COMMENT, 0); }
		public DefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definition; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinitionContext definition() {
		DefinitionContext _localctx = new DefinitionContext(Context, State);
		EnterRule(_localctx, 18, RULE_definition);
		try {
			State = 143;
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 138; classBlock();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 139; structBlock();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 140; enumBlock();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 141; Match(SINGLE_LINE_COMMENT);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 142; Match(DELIMITED_COMMENT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeParamContext : ParserRuleContext {
		public ITerminalNode INTEGER() { return GetToken(FBCParser.INTEGER, 0); }
		public ITerminalNode DASH() { return GetToken(FBCParser.DASH, 0); }
		public ITerminalNode FLOAT_NUMBER() { return GetToken(FBCParser.FLOAT_NUMBER, 0); }
		public ITerminalNode TRUE() { return GetToken(FBCParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(FBCParser.FALSE, 0); }
		public ITerminalNode QUOTED_STRING() { return GetToken(FBCParser.QUOTED_STRING, 0); }
		public AttributeParamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attributeParam; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterAttributeParam(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitAttributeParam(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttributeParam(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributeParamContext attributeParam() {
		AttributeParamContext _localctx = new AttributeParamContext(Context, State);
		EnterRule(_localctx, 20, RULE_attributeParam);
		try {
			State = 154;
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145; Match(INTEGER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 146; Match(DASH);
				State = 147; Match(INTEGER);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 148; Match(FLOAT_NUMBER);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 149; Match(DASH);
				State = 150; Match(FLOAT_NUMBER);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 151; Match(TRUE);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 152; Match(FALSE);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 153; Match(QUOTED_STRING);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public ITerminalNode LPAREN() { return GetToken(FBCParser.LPAREN, 0); }
		public AttributeParamContext[] attributeParam() {
			return GetRuleContexts<AttributeParamContext>();
		}
		public AttributeParamContext attributeParam(int i) {
			return GetRuleContext<AttributeParamContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(FBCParser.RPAREN, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(FBCParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(FBCParser.COMMA, i);
		}
		public AttributeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterAttribute(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitAttribute(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttribute(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributeContext attribute() {
		AttributeContext _localctx = new AttributeContext(Context, State);
		EnterRule(_localctx, 22, RULE_attribute);
		int _la;
		try {
			State = 169;
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 156; Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 157; Match(IDENTIFIER);
				State = 158; Match(LPAREN);
				State = 159; attributeParam();
				State = 164;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==COMMA) {
					{
					{
					State = 160; Match(COMMA);
					State = 161; attributeParam();
					}
					}
					State = 166;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 167; Match(RPAREN);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeBlockContext : ParserRuleContext {
		public ITerminalNode LBRACKET() { return GetToken(FBCParser.LBRACKET, 0); }
		public AttributeContext[] attribute() {
			return GetRuleContexts<AttributeContext>();
		}
		public AttributeContext attribute(int i) {
			return GetRuleContext<AttributeContext>(i);
		}
		public ITerminalNode RBRACKET() { return GetToken(FBCParser.RBRACKET, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(FBCParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(FBCParser.COMMA, i);
		}
		public AttributeBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attributeBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterAttributeBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitAttributeBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttributeBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributeBlockContext attributeBlock() {
		AttributeBlockContext _localctx = new AttributeBlockContext(Context, State);
		EnterRule(_localctx, 24, RULE_attributeBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171; Match(LBRACKET);
			State = 172; attribute();
			State = 177;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==COMMA) {
				{
				{
				State = 173; Match(COMMA);
				State = 174; attribute();
				}
				}
				State = 179;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 180; Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContentsContext : ParserRuleContext {
		public TypeMemberContext typeMember() {
			return GetRuleContext<TypeMemberContext>(0);
		}
		public TypeEventContext typeEvent() {
			return GetRuleContext<TypeEventContext>(0);
		}
		public TypeNativeFunctionContext typeNativeFunction() {
			return GetRuleContext<TypeNativeFunctionContext>(0);
		}
		public TypeManagedFunctionContext typeManagedFunction() {
			return GetRuleContext<TypeManagedFunctionContext>(0);
		}
		public ITerminalNode SINGLE_LINE_COMMENT() { return GetToken(FBCParser.SINGLE_LINE_COMMENT, 0); }
		public ITerminalNode DELIMITED_COMMENT() { return GetToken(FBCParser.DELIMITED_COMMENT, 0); }
		public TypeContentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeContents; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterTypeContents(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitTypeContents(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeContents(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContentsContext typeContents() {
		TypeContentsContext _localctx = new TypeContentsContext(Context, State);
		EnterRule(_localctx, 26, RULE_typeContents);
		try {
			State = 188;
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 182; typeMember();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 183; typeEvent();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 184; typeNativeFunction();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 185; typeManagedFunction();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 186; Match(SINGLE_LINE_COMMENT);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 187; Match(DELIMITED_COMMENT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayModifierContext : ParserRuleContext {
		public ITerminalNode LBRACKET() { return GetToken(FBCParser.LBRACKET, 0); }
		public ITerminalNode RBRACKET() { return GetToken(FBCParser.RBRACKET, 0); }
		public ArrayModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterArrayModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitArrayModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayModifierContext arrayModifier() {
		ArrayModifierContext _localctx = new ArrayModifierContext(Context, State);
		EnterRule(_localctx, 28, RULE_arrayModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190; Match(LBRACKET);
			State = 191; Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeMemberContext : ParserRuleContext {
		public AccessModifierContext accessModifier() {
			return GetRuleContext<AccessModifierContext>(0);
		}
		public MemberTypeContext memberType() {
			return GetRuleContext<MemberTypeContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public ITerminalNode COLON() { return GetToken(FBCParser.COLON, 0); }
		public ITerminalNode INTEGER() { return GetToken(FBCParser.INTEGER, 0); }
		public ITerminalNode SEMICOLON() { return GetToken(FBCParser.SEMICOLON, 0); }
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public ArrayModifierContext arrayModifier() {
			return GetRuleContext<ArrayModifierContext>(0);
		}
		public TypeMemberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeMember; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterTypeMember(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitTypeMember(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeMember(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeMemberContext typeMember() {
		TypeMemberContext _localctx = new TypeMemberContext(Context, State);
		EnterRule(_localctx, 30, RULE_typeMember);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 193; attributeBlock();
				}
				}
				State = 198;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 199; accessModifier();
			State = 200; memberType();
			State = 202;
			_la = TokenStream.La(1);
			if (_la==LBRACKET) {
				{
				State = 201; arrayModifier();
				}
			}

			State = 204; Match(IDENTIFIER);
			State = 205; Match(COLON);
			State = 206; Match(INTEGER);
			State = 207; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeEventContext : ParserRuleContext {
		public ITerminalNode EVENT() { return GetToken(FBCParser.EVENT, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public ITerminalNode SEMICOLON() { return GetToken(FBCParser.SEMICOLON, 0); }
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public TypeEventContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeEvent; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterTypeEvent(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitTypeEvent(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeEvent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeEventContext typeEvent() {
		TypeEventContext _localctx = new TypeEventContext(Context, State);
		EnterRule(_localctx, 32, RULE_typeEvent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 212;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 209; attributeBlock();
				}
				}
				State = 214;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 215; Match(EVENT);
			State = 216; Match(IDENTIFIER);
			State = 217; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeNativeFunctionContext : ParserRuleContext {
		public ITerminalNode NATIVE_START() { return GetToken(FBCParser.NATIVE_START, 0); }
		public ITerminalNode BLOCK_END() { return GetToken(FBCParser.BLOCK_END, 0); }
		public TypeNativeFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeNativeFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterTypeNativeFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitTypeNativeFunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeNativeFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeNativeFunctionContext typeNativeFunction() {
		TypeNativeFunctionContext _localctx = new TypeNativeFunctionContext(Context, State);
		EnterRule(_localctx, 34, RULE_typeNativeFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 219; Match(NATIVE_START);
			State = 220; Match(BLOCK_END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeManagedFunctionContext : ParserRuleContext {
		public ITerminalNode MANAGED_START() { return GetToken(FBCParser.MANAGED_START, 0); }
		public ITerminalNode BLOCK_END() { return GetToken(FBCParser.BLOCK_END, 0); }
		public TypeManagedFunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeManagedFunction; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterTypeManagedFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitTypeManagedFunction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeManagedFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeManagedFunctionContext typeManagedFunction() {
		TypeManagedFunctionContext _localctx = new TypeManagedFunctionContext(Context, State);
		EnterRule(_localctx, 36, RULE_typeManagedFunction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 222; Match(MANAGED_START);
			State = 223; Match(BLOCK_END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockBodyContext : ParserRuleContext {
		public ITerminalNode LBRACE() { return GetToken(FBCParser.LBRACE, 0); }
		public ITerminalNode RBRACE() { return GetToken(FBCParser.RBRACE, 0); }
		public TypeContentsContext[] typeContents() {
			return GetRuleContexts<TypeContentsContext>();
		}
		public TypeContentsContext typeContents(int i) {
			return GetRuleContext<TypeContentsContext>(i);
		}
		public BlockBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterBlockBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitBlockBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockBodyContext blockBody() {
		BlockBodyContext _localctx = new BlockBodyContext(Context, State);
		EnterRule(_localctx, 38, RULE_blockBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225; Match(LBRACE);
			{
			State = 229;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PUBLIC) | (1L << PRIVATE) | (1L << PROTECTED) | (1L << LBRACKET) | (1L << NATIVE_START) | (1L << MANAGED_START) | (1L << EVENT) | (1L << SINGLE_LINE_COMMENT) | (1L << DELIMITED_COMMENT))) != 0)) {
				{
				{
				State = 226; typeContents();
				}
				}
				State = 231;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			}
			State = 232; Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassBlockContext : ParserRuleContext {
		public ITerminalNode CLASS() { return GetToken(FBCParser.CLASS, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public BlockBodyContext blockBody() {
			return GetRuleContext<BlockBodyContext>(0);
		}
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public TypeAlignmentContext typeAlignment() {
			return GetRuleContext<TypeAlignmentContext>(0);
		}
		public ClassInheritanceContext classInheritance() {
			return GetRuleContext<ClassInheritanceContext>(0);
		}
		public ClassBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterClassBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitClassBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassBlockContext classBlock() {
		ClassBlockContext _localctx = new ClassBlockContext(Context, State);
		EnterRule(_localctx, 40, RULE_classBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 237;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 234; attributeBlock();
				}
				}
				State = 239;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 240; Match(CLASS);
			State = 242;
			_la = TokenStream.La(1);
			if (_la==ALIGN) {
				{
				State = 241; typeAlignment();
				}
			}

			State = 244; Match(IDENTIFIER);
			State = 246;
			_la = TokenStream.La(1);
			if (_la==COLON) {
				{
				State = 245; classInheritance();
				}
			}

			State = 248; blockBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassInheritanceContext : ParserRuleContext {
		public ITerminalNode COLON() { return GetToken(FBCParser.COLON, 0); }
		public NamespaceStringContext[] namespaceString() {
			return GetRuleContexts<NamespaceStringContext>();
		}
		public NamespaceStringContext namespaceString(int i) {
			return GetRuleContext<NamespaceStringContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(FBCParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(FBCParser.COMMA, i);
		}
		public ClassInheritanceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classInheritance; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterClassInheritance(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitClassInheritance(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassInheritance(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassInheritanceContext classInheritance() {
		ClassInheritanceContext _localctx = new ClassInheritanceContext(Context, State);
		EnterRule(_localctx, 42, RULE_classInheritance);
		int _la;
		try {
			State = 261;
			switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 250; Match(COLON);
				State = 251; namespaceString();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 252; Match(COLON);
				State = 253; namespaceString();
				State = 258;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==COMMA) {
					{
					{
					State = 254; Match(COMMA);
					State = 255; namespaceString();
					}
					}
					State = 260;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructBlockContext : ParserRuleContext {
		public ITerminalNode STRUCT() { return GetToken(FBCParser.STRUCT, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public BlockBodyContext blockBody() {
			return GetRuleContext<BlockBodyContext>(0);
		}
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public TypeAlignmentContext typeAlignment() {
			return GetRuleContext<TypeAlignmentContext>(0);
		}
		public StructBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterStructBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitStructBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructBlockContext structBlock() {
		StructBlockContext _localctx = new StructBlockContext(Context, State);
		EnterRule(_localctx, 44, RULE_structBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 266;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 263; attributeBlock();
				}
				}
				State = 268;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 269; Match(STRUCT);
			State = 271;
			_la = TokenStream.La(1);
			if (_la==ALIGN) {
				{
				State = 270; typeAlignment();
				}
			}

			State = 273; Match(IDENTIFIER);
			State = 274; blockBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumBlockContext : ParserRuleContext {
		public ITerminalNode ENUM() { return GetToken(FBCParser.ENUM, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public EnumBodyContext enumBody() {
			return GetRuleContext<EnumBodyContext>(0);
		}
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public EnumDataTypeContext enumDataType() {
			return GetRuleContext<EnumDataTypeContext>(0);
		}
		public EnumBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumBlock; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumBlockContext enumBlock() {
		EnumBlockContext _localctx = new EnumBlockContext(Context, State);
		EnterRule(_localctx, 46, RULE_enumBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 276; attributeBlock();
				}
				}
				State = 281;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 282; Match(ENUM);
			State = 283; Match(IDENTIFIER);
			State = 285;
			_la = TokenStream.La(1);
			if (_la==COLON) {
				{
				State = 284; enumDataType();
				}
			}

			State = 287; enumBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumDataTypeContext : ParserRuleContext {
		public ITerminalNode COLON() { return GetToken(FBCParser.COLON, 0); }
		public IntegerTypeContext integerType() {
			return GetRuleContext<IntegerTypeContext>(0);
		}
		public EnumDataTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumDataType; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumDataType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumDataType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumDataType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumDataTypeContext enumDataType() {
		EnumDataTypeContext _localctx = new EnumDataTypeContext(Context, State);
		EnterRule(_localctx, 48, RULE_enumDataType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 289; Match(COLON);
			State = 290; integerType();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumBodyContext : ParserRuleContext {
		public ITerminalNode LBRACE() { return GetToken(FBCParser.LBRACE, 0); }
		public EnumLastMemberContext enumLastMember() {
			return GetRuleContext<EnumLastMemberContext>(0);
		}
		public ITerminalNode RBRACE() { return GetToken(FBCParser.RBRACE, 0); }
		public EnumValueContext[] enumValue() {
			return GetRuleContexts<EnumValueContext>();
		}
		public EnumValueContext enumValue(int i) {
			return GetRuleContext<EnumValueContext>(i);
		}
		public EnumBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumBodyContext enumBody() {
		EnumBodyContext _localctx = new EnumBodyContext(Context, State);
		EnterRule(_localctx, 50, RULE_enumBody);
		try {
			int _alt;
			State = 304;
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 292; Match(LBRACE);
				State = 296;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 293; enumValue();
						}
						} 
					}
					State = 298;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
				}
				State = 299; enumLastMember();
				State = 300; Match(RBRACE);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 302; Match(LBRACE);
				State = 303; Match(RBRACE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumValueContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public ITerminalNode COMMA() { return GetToken(FBCParser.COMMA, 0); }
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public EnumMemberValueContext enumMemberValue() {
			return GetRuleContext<EnumMemberValueContext>(0);
		}
		public EnumValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumValueContext enumValue() {
		EnumValueContext _localctx = new EnumValueContext(Context, State);
		EnterRule(_localctx, 52, RULE_enumValue);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 309;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 306; attributeBlock();
				}
				}
				State = 311;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 312; Match(IDENTIFIER);
			State = 314;
			_la = TokenStream.La(1);
			if (_la==EQUALS) {
				{
				State = 313; enumMemberValue();
				}
			}

			State = 316; Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumLastMemberContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(FBCParser.IDENTIFIER, 0); }
		public EnumTerminatorContext enumTerminator() {
			return GetRuleContext<EnumTerminatorContext>(0);
		}
		public AttributeBlockContext[] attributeBlock() {
			return GetRuleContexts<AttributeBlockContext>();
		}
		public AttributeBlockContext attributeBlock(int i) {
			return GetRuleContext<AttributeBlockContext>(i);
		}
		public EnumMemberValueContext enumMemberValue() {
			return GetRuleContext<EnumMemberValueContext>(0);
		}
		public EnumLastMemberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumLastMember; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumLastMember(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumLastMember(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumLastMember(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumLastMemberContext enumLastMember() {
		EnumLastMemberContext _localctx = new EnumLastMemberContext(Context, State);
		EnterRule(_localctx, 54, RULE_enumLastMember);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 321;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==LBRACKET) {
				{
				{
				State = 318; attributeBlock();
				}
				}
				State = 323;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 324; Match(IDENTIFIER);
			State = 326;
			_la = TokenStream.La(1);
			if (_la==EQUALS) {
				{
				State = 325; enumMemberValue();
				}
			}

			State = 328; enumTerminator();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumMemberValueContext : ParserRuleContext {
		public ITerminalNode EQUALS() { return GetToken(FBCParser.EQUALS, 0); }
		public ITerminalNode INTEGER() { return GetToken(FBCParser.INTEGER, 0); }
		public ITerminalNode DASH() { return GetToken(FBCParser.DASH, 0); }
		public EnumMemberValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumMemberValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumMemberValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumMemberValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumMemberValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumMemberValueContext enumMemberValue() {
		EnumMemberValueContext _localctx = new EnumMemberValueContext(Context, State);
		EnterRule(_localctx, 56, RULE_enumMemberValue);
		try {
			State = 335;
			switch ( Interpreter.AdaptivePredict(TokenStream,34,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 330; Match(EQUALS);
				State = 331; Match(INTEGER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 332; Match(EQUALS);
				State = 333; Match(DASH);
				State = 334; Match(INTEGER);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumTerminatorContext : ParserRuleContext {
		public ITerminalNode COMMA() { return GetToken(FBCParser.COMMA, 0); }
		public EnumTerminatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumTerminator; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterEnumTerminator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitEnumTerminator(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumTerminator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumTerminatorContext enumTerminator() {
		EnumTerminatorContext _localctx = new EnumTerminatorContext(Context, State);
		EnterRule(_localctx, 58, RULE_enumTerminator);
		try {
			State = 339;
			switch (TokenStream.La(1)) {
			case RBRACE:
				EnterOuterAlt(_localctx, 1);
				{
				}
				break;
			case COMMA:
				EnterOuterAlt(_localctx, 2);
				{
				State = 338; Match(COMMA);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeAlignmentContext : ParserRuleContext {
		public ITerminalNode ALIGN() { return GetToken(FBCParser.ALIGN, 0); }
		public ITerminalNode LPAREN() { return GetToken(FBCParser.LPAREN, 0); }
		public ITerminalNode INTEGER() { return GetToken(FBCParser.INTEGER, 0); }
		public ITerminalNode RPAREN() { return GetToken(FBCParser.RPAREN, 0); }
		public TypeAlignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeAlignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.EnterTypeAlignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IFBCListener typedListener = listener as IFBCListener;
			if (typedListener != null) typedListener.ExitTypeAlignment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IFBCVisitor<TResult> typedVisitor = visitor as IFBCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeAlignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeAlignmentContext typeAlignment() {
		TypeAlignmentContext _localctx = new TypeAlignmentContext(Context, State);
		EnterRule(_localctx, 60, RULE_typeAlignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 341; Match(ALIGN);
			State = 342; Match(LPAREN);
			State = 343; Match(INTEGER);
			State = 344; Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x39\x15D\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x4\x19\t\x19\x4\x1A\t\x1A\x4\x1B"+
		"\t\x1B\x4\x1C\t\x1C\x4\x1D\t\x1D\x4\x1E\t\x1E\x4\x1F\t\x1F\x4 \t \x3\x2"+
		"\x3\x2\x3\x2\x3\x2\x3\x2\x3\x2\a\x2G\n\x2\f\x2\xE\x2J\v\x2\x3\x2\x3\x2"+
		"\x5\x2N\n\x2\x3\x3\x3\x3\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3"+
		"\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x5\x4\x61\n\x4\x3\x5\x3"+
		"\x5\x3\x6\x3\x6\x3\x6\x3\a\x3\a\a\aj\n\a\f\a\xE\am\v\a\x3\a\x3\a\x5\a"+
		"q\n\a\x3\b\x3\b\a\bu\n\b\f\b\xE\bx\v\b\x3\b\x3\b\x5\b|\n\b\x3\t\x3\t\x3"+
		"\t\x3\t\x3\n\x3\n\x3\n\x3\n\a\n\x86\n\n\f\n\xE\n\x89\v\n\x5\n\x8B\n\n"+
		"\x3\v\x3\v\x3\v\x3\v\x3\v\x5\v\x92\n\v\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3"+
		"\f\x3\f\x3\f\x5\f\x9D\n\f\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\a\r\xA5\n\r\f"+
		"\r\xE\r\xA8\v\r\x3\r\x3\r\x5\r\xAC\n\r\x3\xE\x3\xE\x3\xE\x3\xE\a\xE\xB2"+
		"\n\xE\f\xE\xE\xE\xB5\v\xE\x3\xE\x3\xE\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x3"+
		"\xF\x5\xF\xBF\n\xF\x3\x10\x3\x10\x3\x10\x3\x11\a\x11\xC5\n\x11\f\x11\xE"+
		"\x11\xC8\v\x11\x3\x11\x3\x11\x3\x11\x5\x11\xCD\n\x11\x3\x11\x3\x11\x3"+
		"\x11\x3\x11\x3\x11\x3\x12\a\x12\xD5\n\x12\f\x12\xE\x12\xD8\v\x12\x3\x12"+
		"\x3\x12\x3\x12\x3\x12\x3\x13\x3\x13\x3\x13\x3\x14\x3\x14\x3\x14\x3\x15"+
		"\x3\x15\a\x15\xE6\n\x15\f\x15\xE\x15\xE9\v\x15\x3\x15\x3\x15\x3\x16\a"+
		"\x16\xEE\n\x16\f\x16\xE\x16\xF1\v\x16\x3\x16\x3\x16\x5\x16\xF5\n\x16\x3"+
		"\x16\x3\x16\x5\x16\xF9\n\x16\x3\x16\x3\x16\x3\x17\x3\x17\x3\x17\x3\x17"+
		"\x3\x17\x3\x17\a\x17\x103\n\x17\f\x17\xE\x17\x106\v\x17\x5\x17\x108\n"+
		"\x17\x3\x18\a\x18\x10B\n\x18\f\x18\xE\x18\x10E\v\x18\x3\x18\x3\x18\x5"+
		"\x18\x112\n\x18\x3\x18\x3\x18\x3\x18\x3\x19\a\x19\x118\n\x19\f\x19\xE"+
		"\x19\x11B\v\x19\x3\x19\x3\x19\x3\x19\x5\x19\x120\n\x19\x3\x19\x3\x19\x3"+
		"\x1A\x3\x1A\x3\x1A\x3\x1B\x3\x1B\a\x1B\x129\n\x1B\f\x1B\xE\x1B\x12C\v"+
		"\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x5\x1B\x133\n\x1B\x3\x1C\a\x1C"+
		"\x136\n\x1C\f\x1C\xE\x1C\x139\v\x1C\x3\x1C\x3\x1C\x5\x1C\x13D\n\x1C\x3"+
		"\x1C\x3\x1C\x3\x1D\a\x1D\x142\n\x1D\f\x1D\xE\x1D\x145\v\x1D\x3\x1D\x3"+
		"\x1D\x5\x1D\x149\n\x1D\x3\x1D\x3\x1D\x3\x1E\x3\x1E\x3\x1E\x3\x1E\x3\x1E"+
		"\x5\x1E\x152\n\x1E\x3\x1F\x3\x1F\x5\x1F\x156\n\x1F\x3 \x3 \x3 \x3 \x3"+
		" \x3 \x2\x2!\x2\x4\x6\b\n\f\xE\x10\x12\x14\x16\x18\x1A\x1C\x1E \"$&(*"+
		",.\x30\x32\x34\x36\x38:<>\x2\x4\x3\x2\x3\x5\x3\x2\b\xF\x17D\x2M\x3\x2"+
		"\x2\x2\x4O\x3\x2\x2\x2\x6`\x3\x2\x2\x2\b\x62\x3\x2\x2\x2\n\x64\x3\x2\x2"+
		"\x2\fp\x3\x2\x2\x2\xE{\x3\x2\x2\x2\x10}\x3\x2\x2\x2\x12\x8A\x3\x2\x2\x2"+
		"\x14\x91\x3\x2\x2\x2\x16\x9C\x3\x2\x2\x2\x18\xAB\x3\x2\x2\x2\x1A\xAD\x3"+
		"\x2\x2\x2\x1C\xBE\x3\x2\x2\x2\x1E\xC0\x3\x2\x2\x2 \xC6\x3\x2\x2\x2\"\xD6"+
		"\x3\x2\x2\x2$\xDD\x3\x2\x2\x2&\xE0\x3\x2\x2\x2(\xE3\x3\x2\x2\x2*\xEF\x3"+
		"\x2\x2\x2,\x107\x3\x2\x2\x2.\x10C\x3\x2\x2\x2\x30\x119\x3\x2\x2\x2\x32"+
		"\x123\x3\x2\x2\x2\x34\x132\x3\x2\x2\x2\x36\x137\x3\x2\x2\x2\x38\x143\x3"+
		"\x2\x2\x2:\x151\x3\x2\x2\x2<\x155\x3\x2\x2\x2>\x157\x3\x2\x2\x2@\x41\x5"+
		"\f\a\x2\x41\x42\x5\xE\b\x2\x42\x43\a\x2\x2\x3\x43N\x3\x2\x2\x2\x44H\x5"+
		"\f\a\x2\x45G\x5\x14\v\x2\x46\x45\x3\x2\x2\x2GJ\x3\x2\x2\x2H\x46\x3\x2"+
		"\x2\x2HI\x3\x2\x2\x2IK\x3\x2\x2\x2JH\x3\x2\x2\x2KL\a\x2\x2\x3LN\x3\x2"+
		"\x2\x2M@\x3\x2\x2\x2M\x44\x3\x2\x2\x2N\x3\x3\x2\x2\x2OP\t\x2\x2\x2P\x5"+
		"\x3\x2\x2\x2Q\x61\a\x6\x2\x2R\x61\a\a\x2\x2S\x61\a\x10\x2\x2T\x61\a\x11"+
		"\x2\x2U\x61\a\x12\x2\x2V\x61\a\x13\x2\x2W\x61\a\b\x2\x2X\x61\a\t\x2\x2"+
		"Y\x61\a\n\x2\x2Z\x61\a\v\x2\x2[\x61\a\f\x2\x2\\\x61\a\r\x2\x2]\x61\a\xE"+
		"\x2\x2^\x61\a\xF\x2\x2_\x61\x5\x12\n\x2`Q\x3\x2\x2\x2`R\x3\x2\x2\x2`S"+
		"\x3\x2\x2\x2`T\x3\x2\x2\x2`U\x3\x2\x2\x2`V\x3\x2\x2\x2`W\x3\x2\x2\x2`"+
		"X\x3\x2\x2\x2`Y\x3\x2\x2\x2`Z\x3\x2\x2\x2`[\x3\x2\x2\x2`\\\x3\x2\x2\x2"+
		"`]\x3\x2\x2\x2`^\x3\x2\x2\x2`_\x3\x2\x2\x2\x61\a\x3\x2\x2\x2\x62\x63\t"+
		"\x3\x2\x2\x63\t\x3\x2\x2\x2\x64\x65\a(\x2\x2\x65\x66\a\x37\x2\x2\x66\v"+
		"\x3\x2\x2\x2gq\x3\x2\x2\x2hj\x5\n\x6\x2ih\x3\x2\x2\x2jm\x3\x2\x2\x2ki"+
		"\x3\x2\x2\x2kl\x3\x2\x2\x2lq\x3\x2\x2\x2mk\x3\x2\x2\x2nq\a\x34\x2\x2o"+
		"q\a\x35\x2\x2pg\x3\x2\x2\x2pk\x3\x2\x2\x2pn\x3\x2\x2\x2po\x3\x2\x2\x2"+
		"q\r\x3\x2\x2\x2rv\x5\x10\t\x2su\x5\x14\v\x2ts\x3\x2\x2\x2ux\x3\x2\x2\x2"+
		"vt\x3\x2\x2\x2vw\x3\x2\x2\x2w|\x3\x2\x2\x2xv\x3\x2\x2\x2y|\a\x34\x2\x2"+
		"z|\a\x35\x2\x2{r\x3\x2\x2\x2{y\x3\x2\x2\x2{z\x3\x2\x2\x2|\xF\x3\x2\x2"+
		"\x2}~\a#\x2\x2~\x7F\x5\x12\n\x2\x7F\x80\a-\x2\x2\x80\x11\x3\x2\x2\x2\x81"+
		"\x8B\a\x31\x2\x2\x82\x87\a\x31\x2\x2\x83\x84\a.\x2\x2\x84\x86\a\x31\x2"+
		"\x2\x85\x83\x3\x2\x2\x2\x86\x89\x3\x2\x2\x2\x87\x85\x3\x2\x2\x2\x87\x88"+
		"\x3\x2\x2\x2\x88\x8B\x3\x2\x2\x2\x89\x87\x3\x2\x2\x2\x8A\x81\x3\x2\x2"+
		"\x2\x8A\x82\x3\x2\x2\x2\x8B\x13\x3\x2\x2\x2\x8C\x92\x5*\x16\x2\x8D\x92"+
		"\x5.\x18\x2\x8E\x92\x5\x30\x19\x2\x8F\x92\a\x34\x2\x2\x90\x92\a\x35\x2"+
		"\x2\x91\x8C\x3\x2\x2\x2\x91\x8D\x3\x2\x2\x2\x91\x8E\x3\x2\x2\x2\x91\x8F"+
		"\x3\x2\x2\x2\x91\x90\x3\x2\x2\x2\x92\x15\x3\x2\x2\x2\x93\x9D\a\x33\x2"+
		"\x2\x94\x95\a\x30\x2\x2\x95\x9D\a\x33\x2\x2\x96\x9D\a\x32\x2\x2\x97\x98"+
		"\a\x30\x2\x2\x98\x9D\a\x32\x2\x2\x99\x9D\a\x14\x2\x2\x9A\x9D\a\x15\x2"+
		"\x2\x9B\x9D\a\x38\x2\x2\x9C\x93\x3\x2\x2\x2\x9C\x94\x3\x2\x2\x2\x9C\x96"+
		"\x3\x2\x2\x2\x9C\x97\x3\x2\x2\x2\x9C\x99\x3\x2\x2\x2\x9C\x9A\x3\x2\x2"+
		"\x2\x9C\x9B\x3\x2\x2\x2\x9D\x17\x3\x2\x2\x2\x9E\xAC\a\x31\x2\x2\x9F\xA0"+
		"\a\x31\x2\x2\xA0\xA1\a\x1E\x2\x2\xA1\xA6\x5\x16\f\x2\xA2\xA3\a+\x2\x2"+
		"\xA3\xA5\x5\x16\f\x2\xA4\xA2\x3\x2\x2\x2\xA5\xA8\x3\x2\x2\x2\xA6\xA4\x3"+
		"\x2\x2\x2\xA6\xA7\x3\x2\x2\x2\xA7\xA9\x3\x2\x2\x2\xA8\xA6\x3\x2\x2\x2"+
		"\xA9\xAA\a\x1F\x2\x2\xAA\xAC\x3\x2\x2\x2\xAB\x9E\x3\x2\x2\x2\xAB\x9F\x3"+
		"\x2\x2\x2\xAC\x19\x3\x2\x2\x2\xAD\xAE\a\x1A\x2\x2\xAE\xB3\x5\x18\r\x2"+
		"\xAF\xB0\a+\x2\x2\xB0\xB2\x5\x18\r\x2\xB1\xAF\x3\x2\x2\x2\xB2\xB5\x3\x2"+
		"\x2\x2\xB3\xB1\x3\x2\x2\x2\xB3\xB4\x3\x2\x2\x2\xB4\xB6\x3\x2\x2\x2\xB5"+
		"\xB3\x3\x2\x2\x2\xB6\xB7\a\x1B\x2\x2\xB7\x1B\x3\x2\x2\x2\xB8\xBF\x5 \x11"+
		"\x2\xB9\xBF\x5\"\x12\x2\xBA\xBF\x5$\x13\x2\xBB\xBF\x5&\x14\x2\xBC\xBF"+
		"\a\x34\x2\x2\xBD\xBF\a\x35\x2\x2\xBE\xB8\x3\x2\x2\x2\xBE\xB9\x3\x2\x2"+
		"\x2\xBE\xBA\x3\x2\x2\x2\xBE\xBB\x3\x2\x2\x2\xBE\xBC\x3\x2\x2\x2\xBE\xBD"+
		"\x3\x2\x2\x2\xBF\x1D\x3\x2\x2\x2\xC0\xC1\a\x1A\x2\x2\xC1\xC2\a\x1B\x2"+
		"\x2\xC2\x1F\x3\x2\x2\x2\xC3\xC5\x5\x1A\xE\x2\xC4\xC3\x3\x2\x2\x2\xC5\xC8"+
		"\x3\x2\x2\x2\xC6\xC4\x3\x2\x2\x2\xC6\xC7\x3\x2\x2\x2\xC7\xC9\x3\x2\x2"+
		"\x2\xC8\xC6\x3\x2\x2\x2\xC9\xCA\x5\x4\x3\x2\xCA\xCC\x5\x6\x4\x2\xCB\xCD"+
		"\x5\x1E\x10\x2\xCC\xCB\x3\x2\x2\x2\xCC\xCD\x3\x2\x2\x2\xCD\xCE\x3\x2\x2"+
		"\x2\xCE\xCF\a\x31\x2\x2\xCF\xD0\a,\x2\x2\xD0\xD1\a\x33\x2\x2\xD1\xD2\a"+
		"-\x2\x2\xD2!\x3\x2\x2\x2\xD3\xD5\x5\x1A\xE\x2\xD4\xD3\x3\x2\x2\x2\xD5"+
		"\xD8\x3\x2\x2\x2\xD6\xD4\x3\x2\x2\x2\xD6\xD7\x3\x2\x2\x2\xD7\xD9\x3\x2"+
		"\x2\x2\xD8\xD6\x3\x2\x2\x2\xD9\xDA\a\'\x2\x2\xDA\xDB\a\x31\x2\x2\xDB\xDC"+
		"\a-\x2\x2\xDC#\x3\x2\x2\x2\xDD\xDE\a \x2\x2\xDE\xDF\a\"\x2\x2\xDF%\x3"+
		"\x2\x2\x2\xE0\xE1\a!\x2\x2\xE1\xE2\a\"\x2\x2\xE2\'\x3\x2\x2\x2\xE3\xE7"+
		"\a\x1C\x2\x2\xE4\xE6\x5\x1C\xF\x2\xE5\xE4\x3\x2\x2\x2\xE6\xE9\x3\x2\x2"+
		"\x2\xE7\xE5\x3\x2\x2\x2\xE7\xE8\x3\x2\x2\x2\xE8\xEA\x3\x2\x2\x2\xE9\xE7"+
		"\x3\x2\x2\x2\xEA\xEB\a\x1D\x2\x2\xEB)\x3\x2\x2\x2\xEC\xEE\x5\x1A\xE\x2"+
		"\xED\xEC\x3\x2\x2\x2\xEE\xF1\x3\x2\x2\x2\xEF\xED\x3\x2\x2\x2\xEF\xF0\x3"+
		"\x2\x2\x2\xF0\xF2\x3\x2\x2\x2\xF1\xEF\x3\x2\x2\x2\xF2\xF4\a$\x2\x2\xF3"+
		"\xF5\x5> \x2\xF4\xF3\x3\x2\x2\x2\xF4\xF5\x3\x2\x2\x2\xF5\xF6\x3\x2\x2"+
		"\x2\xF6\xF8\a\x31\x2\x2\xF7\xF9\x5,\x17\x2\xF8\xF7\x3\x2\x2\x2\xF8\xF9"+
		"\x3\x2\x2\x2\xF9\xFA\x3\x2\x2\x2\xFA\xFB\x5(\x15\x2\xFB+\x3\x2\x2\x2\xFC"+
		"\xFD\a,\x2\x2\xFD\x108\x5\x12\n\x2\xFE\xFF\a,\x2\x2\xFF\x104\x5\x12\n"+
		"\x2\x100\x101\a+\x2\x2\x101\x103\x5\x12\n\x2\x102\x100\x3\x2\x2\x2\x103"+
		"\x106\x3\x2\x2\x2\x104\x102\x3\x2\x2\x2\x104\x105\x3\x2\x2\x2\x105\x108"+
		"\x3\x2\x2\x2\x106\x104\x3\x2\x2\x2\x107\xFC\x3\x2\x2\x2\x107\xFE\x3\x2"+
		"\x2\x2\x108-\x3\x2\x2\x2\x109\x10B\x5\x1A\xE\x2\x10A\x109\x3\x2\x2\x2"+
		"\x10B\x10E\x3\x2\x2\x2\x10C\x10A\x3\x2\x2\x2\x10C\x10D\x3\x2\x2\x2\x10D"+
		"\x10F\x3\x2\x2\x2\x10E\x10C\x3\x2\x2\x2\x10F\x111\a&\x2\x2\x110\x112\x5"+
		"> \x2\x111\x110\x3\x2\x2\x2\x111\x112\x3\x2\x2\x2\x112\x113\x3\x2\x2\x2"+
		"\x113\x114\a\x31\x2\x2\x114\x115\x5(\x15\x2\x115/\x3\x2\x2\x2\x116\x118"+
		"\x5\x1A\xE\x2\x117\x116\x3\x2\x2\x2\x118\x11B\x3\x2\x2\x2\x119\x117\x3"+
		"\x2\x2\x2\x119\x11A\x3\x2\x2\x2\x11A\x11C\x3\x2\x2\x2\x11B\x119\x3\x2"+
		"\x2\x2\x11C\x11D\a%\x2\x2\x11D\x11F\a\x31\x2\x2\x11E\x120\x5\x32\x1A\x2"+
		"\x11F\x11E\x3\x2\x2\x2\x11F\x120\x3\x2\x2\x2\x120\x121\x3\x2\x2\x2\x121"+
		"\x122\x5\x34\x1B\x2\x122\x31\x3\x2\x2\x2\x123\x124\a,\x2\x2\x124\x125"+
		"\x5\b\x5\x2\x125\x33\x3\x2\x2\x2\x126\x12A\a\x1C\x2\x2\x127\x129\x5\x36"+
		"\x1C\x2\x128\x127\x3\x2\x2\x2\x129\x12C\x3\x2\x2\x2\x12A\x128\x3\x2\x2"+
		"\x2\x12A\x12B\x3\x2\x2\x2\x12B\x12D\x3\x2\x2\x2\x12C\x12A\x3\x2\x2\x2"+
		"\x12D\x12E\x5\x38\x1D\x2\x12E\x12F\a\x1D\x2\x2\x12F\x133\x3\x2\x2\x2\x130"+
		"\x131\a\x1C\x2\x2\x131\x133\a\x1D\x2\x2\x132\x126\x3\x2\x2\x2\x132\x130"+
		"\x3\x2\x2\x2\x133\x35\x3\x2\x2\x2\x134\x136\x5\x1A\xE\x2\x135\x134\x3"+
		"\x2\x2\x2\x136\x139\x3\x2\x2\x2\x137\x135\x3\x2\x2\x2\x137\x138\x3\x2"+
		"\x2\x2\x138\x13A\x3\x2\x2\x2\x139\x137\x3\x2\x2\x2\x13A\x13C\a\x31\x2"+
		"\x2\x13B\x13D\x5:\x1E\x2\x13C\x13B\x3\x2\x2\x2\x13C\x13D\x3\x2\x2\x2\x13D"+
		"\x13E\x3\x2\x2\x2\x13E\x13F\a+\x2\x2\x13F\x37\x3\x2\x2\x2\x140\x142\x5"+
		"\x1A\xE\x2\x141\x140\x3\x2\x2\x2\x142\x145\x3\x2\x2\x2\x143\x141\x3\x2"+
		"\x2\x2\x143\x144\x3\x2\x2\x2\x144\x146\x3\x2\x2\x2\x145\x143\x3\x2\x2"+
		"\x2\x146\x148\a\x31\x2\x2\x147\x149\x5:\x1E\x2\x148\x147\x3\x2\x2\x2\x148"+
		"\x149\x3\x2\x2\x2\x149\x14A\x3\x2\x2\x2\x14A\x14B\x5<\x1F\x2\x14B\x39"+
		"\x3\x2\x2\x2\x14C\x14D\a/\x2\x2\x14D\x152\a\x33\x2\x2\x14E\x14F\a/\x2"+
		"\x2\x14F\x150\a\x30\x2\x2\x150\x152\a\x33\x2\x2\x151\x14C\x3\x2\x2\x2"+
		"\x151\x14E\x3\x2\x2\x2\x152;\x3\x2\x2\x2\x153\x156\x3\x2\x2\x2\x154\x156"+
		"\a+\x2\x2\x155\x153\x3\x2\x2\x2\x155\x154\x3\x2\x2\x2\x156=\x3\x2\x2\x2"+
		"\x157\x158\a)\x2\x2\x158\x159\a\x1E\x2\x2\x159\x15A\a\x33\x2\x2\x15A\x15B"+
		"\a\x1F\x2\x2\x15B?\x3\x2\x2\x2&HM`kpv{\x87\x8A\x91\x9C\xA6\xAB\xB3\xBE"+
		"\xC6\xCC\xD6\xE7\xEF\xF4\xF8\x104\x107\x10C\x111\x119\x11F\x12A\x132\x137"+
		"\x13C\x143\x148\x151\x155";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
