//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FBC.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FBCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IFBCVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.fbc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFbc([NotNull] FBCParser.FbcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessModifier([NotNull] FBCParser.AccessModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.memberType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberType([NotNull] FBCParser.MemberTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] FBCParser.IntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.fileInclude"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileInclude([NotNull] FBCParser.FileIncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.includeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeBlock([NotNull] FBCParser.IncludeBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.namespaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceBlock([NotNull] FBCParser.NamespaceBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] FBCParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.namespaceString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceString([NotNull] FBCParser.NamespaceStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] FBCParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.attributeParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeParam([NotNull] FBCParser.AttributeParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] FBCParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.attributeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeBlock([NotNull] FBCParser.AttributeBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.typeContents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeContents([NotNull] FBCParser.TypeContentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.arrayModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayModifier([NotNull] FBCParser.ArrayModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.typeMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeMember([NotNull] FBCParser.TypeMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.typeEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeEvent([NotNull] FBCParser.TypeEventContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.typeNativeFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeNativeFunction([NotNull] FBCParser.TypeNativeFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.typeManagedFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeManagedFunction([NotNull] FBCParser.TypeManagedFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.blockBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockBody([NotNull] FBCParser.BlockBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.classBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBlock([NotNull] FBCParser.ClassBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.classInheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInheritance([NotNull] FBCParser.ClassInheritanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.structBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBlock([NotNull] FBCParser.StructBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBlock([NotNull] FBCParser.EnumBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumDataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDataType([NotNull] FBCParser.EnumDataTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] FBCParser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] FBCParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumLastMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLastMember([NotNull] FBCParser.EnumLastMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumMemberValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumMemberValue([NotNull] FBCParser.EnumMemberValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.enumTerminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumTerminator([NotNull] FBCParser.EnumTerminatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FBCParser.typeAlignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeAlignment([NotNull] FBCParser.TypeAlignmentContext context);
}
