///////////////////////////////////////////////////////////////
//                                                           //
// This is an automatically generated file.                  //
// Do *NOT* modify unless you really know what you're doing. //
//                                                           //
///////////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Collections.Generic;
using Newtonsoft.Json;
using RimeLib.IO;
using RimeLib.Frostbite.Core;
using RimeLib.Serialization.Attributes;
using RimeLib.Serialization;
using RimeLib.Serialization.Frostbite2_0.Ebx;
using CommunityToolkit.Mvvm.ComponentModel;

namespace fb
{
	[ContainerType(4, 4)]
	public enum ShaderProgram : int
	{
		ShaderProgram_DebugRender_Font2d = 0,
		ShaderProgram_DebugRender_FontShadow2d = 1,
		ShaderProgram_DebugRender_Color2d = 2,
		ShaderProgram_DebugRender_Color3d = 3,
		ShaderProgram_DebugRender_Lit3d = 4,
		ShaderProgram_DebugRender_LitGrid3d = 5,
		ShaderProgram_SimpleWhite = 6,
		ShaderProgram_MaterialID = 7,
		ShaderProgram_DownsampleQuarter = 8,
		ShaderProgram_DownsampleQuarterZ = 9,
		ShaderProgram_DownsampleHalf = 10,
		ShaderProgram_DownsampleDepthHalfSingleSample = 11,
		ShaderProgram_DownsampleHalfGrayscaleLog = 12,
		ShaderProgram_DownsampleCubeHalfPoisson13 = 13,
		ShaderProgram_DownsampleCubeHalfPoisson13Clamped = 14,
		ShaderProgram_SeperableFilter = 15,
		ShaderProgram_GaussianBlurRgb15HCube = 16,
		ShaderProgram_GaussianBlurRgb15VCube = 17,
		ShaderProgram_FastGaussian9H = 18,
		ShaderProgram_FastGaussian9V = 19,
		ShaderProgram_GreyscaleGaussian9H = 20,
		ShaderProgram_GreyscaleGaussian9V = 21,
		ShaderProgram_CosineBlurRgbHCube = 22,
		ShaderProgram_CosineBlurRgbVCube = 23,
		ShaderProgram_GaussianBlurRgba15HCube = 24,
		ShaderProgram_GaussianBlurRgba15VCube = 25,
		ShaderProgram_CosineBlurRgbaHCube = 26,
		ShaderProgram_CosineBlurRgbaVCube = 27,
		ShaderProgram_Tex2d = 28,
		ShaderProgram_Tex2dConstantAlpha = 29,
		ShaderProgram_Tex2dSaturateAlpha = 30,
		ShaderProgram_Tex2dAlpha = 31,
		ShaderProgram_Tex2dAlphaOverlayAdd = 32,
		ShaderProgram_Tex2dAlphaOverlayLerp = 33,
		ShaderProgram_Tex2dPow = 34,
		ShaderProgram_Tex2dPowAlpha = 35,
		ShaderProgram_Tex2dMrt2 = 36,
		ShaderProgram_Tex2dMrt3 = 37,
		ShaderProgram_Tex2dMrt4 = 38,
		ShaderProgram_Tex2dGrayscaleLog = 39,
		ShaderProgram_Tex3d = 40,
		ShaderProgram_TexCube = 41,
		ShaderProgram_TexCubeAlpha = 42,
		ShaderProgram_TexCubeAlphaOverlayAdd = 43,
		ShaderProgram_TexCubeAlphaOverlayLerp = 44,
		ShaderProgram_Color = 45,
		ShaderProgram_Tonemap = 46,
		ShaderProgram_ColorGrade = 47,
		ShaderProgram_Dof = 48,
		ShaderProgram_UnprojectDepthBuffer = 49,
		ShaderProgram_UnprojectDepthBufferHalf = 50,
		ShaderProgram_UnprojectDepthBufferMsaa = 51,
		ShaderProgram_SingleDepthSampleMsaa = 52,
		ShaderProgram_MaxDepthSampleMsaa = 53,
		ShaderProgram_TexYCrCb = 54,
		ShaderProgram_CombineTextures2 = 55,
		ShaderProgram_CombineTextures3 = 56,
		ShaderProgram_CombineTextures4 = 57,
		ShaderProgram_CombineTextures5 = 58,
		ShaderProgram_CombineTextures6 = 59,
		ShaderProgram_CombineTextures2Bilinear = 60,
		ShaderProgram_CombineTextures3Bilinear = 61,
		ShaderProgram_CombineTextures4Bilinear = 62,
		ShaderProgram_CombineTextures5Bilinear = 63,
		ShaderProgram_CombineTextures6Bilinear = 64,
		ShaderProgram_CombineOpaqueAndTrans2d = 65,
		ShaderProgram_CombineOpaqueAndTransCube = 66,
		ShaderProgram_CombineOpaqueAndTrans2dSpecial = 67,
		ShaderProgram_CombineOpaqueAndTransCubeSpecial = 68,
		ShaderProgram_CrtHudFx = 69,
		ShaderProgram_CrtAnalogLinkHudFx = 70,
		ShaderProgram_RadialBlur = 71,
		ShaderProgram_PoissonRadialBlur = 72,
		ShaderProgram_ChromaticAberrationWithRadialBlend = 73,
		ShaderProgram_FLIR = 74,
		ShaderProgram_ColorTint = 75,
		ShaderProgram_WriteZ = 76,
		ShaderProgram_WriteHalfResZ = 77,
		ShaderProgram_WriteHalfResZFat = 78,
		ShaderProgram_WriteHalfResZAverage = 79,
		ShaderProgram_LinearZ = 80,
		ShaderProgram_ParticleVertexShadows = 81,
		ShaderProgram_ParticleVertexShadowsAccum = 82,
		ShaderProgram_ParticleVertexShadowsAccumBlend = 83,
		ShaderProgram_HalfResUpsampleBilateral = 84,
		ShaderProgram_HalfResUpsampleBilateralTiled = 85,
		ShaderProgram_HalfResUpsampleBilinearTiled = 86,
		ShaderProgram_HalfResCategorize = 87,
		ShaderProgram_HalfResCategorizeDownsample = 88,
		ShaderProgram_DigitalDistortion = 89,
		ShaderProgram_MotionBlur = 90,
		ShaderProgram_CalcVelocityFromZBuffer = 91,
		ShaderProgram_FXAA = 92,
		ShaderProgram_HorizonBasedAO = 93,
		ShaderProgram_HorizonBasedAO_BlurPS = 94,
		ShaderProgram_HorizonBasedAO_BlurCS = 95,
		ShaderProgram_HorizonBasedAO_PackAODepth = 96,
		ShaderProgram_HorizonBasedAO_CompositeTemporal = 97,
		ShaderProgram_HorizonBasedAO_NoiseDetection = 98,
		ShaderProgram_SSAO = 99,
		ShaderProgram_SSAO_DilateDraw = 100,
		ShaderProgram_LightTileDownsampleHalf = 101,
		ShaderProgram_LightTileDownsampleHalfStage2 = 102,
		ShaderProgram_LightTileDownsampleHalfStage3 = 103,
		ShaderProgram_TiledLightVisibility_Point = 104,
		ShaderProgram_TiledLightVisibility_Spot = 105,
		ShaderProgram_TiledLightVisibility_Line = 106,
		ShaderProgram_TiledLightVisibility_CalcTileFrustaData = 107,
		ShaderProgram_DeferredGBufferSimpleFixup = 108,
		ShaderProgram_MsaaClassify = 109,
		ShaderProgram_DeferredPointLight = 110,
		ShaderProgram_DeferredPointLightCS = 111,
		ShaderProgram_DeferredPointLightTile = 112,
		ShaderProgram_DeferredPointLightZ = 113,
		ShaderProgram_DeferredLineLight = 114,
		ShaderProgram_DeferredLineLightTile = 115,
		ShaderProgram_DeferredSpotLight = 116,
		ShaderProgram_DeferredSpotLightZ = 117,
		ShaderProgram_DeferredConeLight = 118,
		ShaderProgram_DeferredConeLightTile = 119,
		ShaderProgram_DeferredOutdoorLight = 120,
		ShaderProgram_DeferredOutdoorLightTile = 121,
		ShaderProgram_DeferredShadow = 122,
		ShaderProgram_Sky = 123,
		ShaderProgram_HeightfieldTessellation = 124,
		ShaderProgram_XenonMemCopy = 125,
		ShaderProgram_XenonFastUntile = 126,
		ShaderProgram_XenonFastDepthStencilFill = 127,
		ShaderProgram_XenonFastDepthStencilFill_ZOnly = 128,
		ShaderProgram_XenonJobEnable = 129,
		ShaderProgram_Ui_Textured = 130,
		ShaderProgram_Ui_Textured2 = 131,
		ShaderProgram_Ui_Textured3 = 132,
		ShaderProgram_Ui_Textured2GlobalColor = 133,
		ShaderProgram_Ui_Scaleform_StripSolidColor = 134,
		ShaderProgram_Ui_Scaleform_StripCxformTextureMultiply = 135,
		ShaderProgram_Ui_Scaleform_StripCxformTexture = 136,
		ShaderProgram_Ui_Scaleform_StripCxformGauraudNoAddAlpha = 137,
		ShaderProgram_Ui_Scaleform_StripCxformGauraud = 138,
		ShaderProgram_Ui_Scaleform_StripCxformGauraudTexture = 139,
		ShaderProgram_Ui_Scaleform_StripCxform2Texture = 140,
		ShaderProgram_Ui_Scaleform_StripCxformGauraudMultiply = 141,
		ShaderProgram_Ui_Scaleform_StripCxformGauraudMultiplyNoAddAlpha = 142,
		ShaderProgram_Ui_Scaleform_StripCxformGauraudMultiplyTexture = 143,
		ShaderProgram_Ui_Scaleform_StripCxformMultiply2Texture = 144,
		ShaderProgram_Ui_Scaleform_XY16iC32SolidColor = 145,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformTextureMultiply = 146,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformTexture = 147,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformGauraudNoAddAlpha = 148,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformGauraud = 149,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformGauraudTexture = 150,
		ShaderProgram_Ui_Scaleform_XY16iC32Cxform2Texture = 151,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformGauraudMultiply = 152,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformGauraudMultiplyNoAddAlpha = 153,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformGauraudMultiplyTexture = 154,
		ShaderProgram_Ui_Scaleform_XY16iC32CxformMultiply2Texture = 155,
		ShaderProgram_Ui_Scaleform_XY16iCF32SolidColor = 156,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformTextureMultiply = 157,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformTexture = 158,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformGauraudNoAddAlpha = 159,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformGauraud = 160,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformGauraudTexture = 161,
		ShaderProgram_Ui_Scaleform_XY16iCF32Cxform2Texture = 162,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformGauraudMultiply = 163,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformGauraudMultiplyNoAddAlpha = 164,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformGauraudMultiplyTexture = 165,
		ShaderProgram_Ui_Scaleform_XY16iCF32CxformMultiply2Texture = 166,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2SolidColor = 167,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformTextureMultiply = 168,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformTexture = 169,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformGauraudNoAddAlpha = 170,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformGauraud = 171,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformGauraudTexture = 172,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2Cxform2Texture = 173,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformGauraudMultiply = 174,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformGauraudMultiplyNoAddAlpha = 175,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformGauraudMultiplyTexture = 176,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2CxformMultiply2Texture = 177,
		ShaderProgram_Ui_Scaleform_GlyphTextTextureAlpha = 178,
		ShaderProgram_Ui_Scaleform_GlyphTextTextureColorMultiply = 179,
		ShaderProgram_Ui_Scaleform_GlyphTextTextureColor = 180,
		ShaderProgram_Ui_Scaleform_StripFilterBlur = 181,
		ShaderProgram_Ui_Scaleform_StripFilterShadow = 182,
		ShaderProgram_Ui_Scaleform_XY16iC32FilterBlur = 183,
		ShaderProgram_Ui_Scaleform_XY16iC32FilterShadow = 184,
		ShaderProgram_Ui_Scaleform_XY16iCF32FilterBlur = 185,
		ShaderProgram_Ui_Scaleform_XY16iCF32FilterShadow = 186,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2FilterBlur = 187,
		ShaderProgram_Ui_Scaleform_XY16iCF32_T2FilterShadow = 188,
		ShaderProgram_Ui_Scaleform_GlyphFilterBlur = 189,
		ShaderProgram_Ui_Scaleform_GlyphFilterShadow = 190,
		ShaderProgram_Ui_Minimap = 191,
		ShaderProgram_Ui_MinimapIcon = 192,
		ShaderProgram_Ui_CombatArea = 193,
		ShaderProgram_ExperimentShader_A = 194,
		ShaderProgram_ExperimentShader_B = 195,
		ShaderProgram_TextureCompress_A = 196,
		ShaderProgram_TextureCompress_DXT1 = 197,
		ShaderProgram_TextureCompress_DXT5 = 198,
		ShaderProgram_ErrorDifferenceSurface_RGB = 199,
		ShaderProgram_ErrorDifferenceSurface_Alpha = 200,
		ShaderProgram_XenonEncodeDXT5MemExport = 201,
		ShaderProgram_TerrainEncodeSurface_A = 202,
		ShaderProgram_TerrainEncodeSurface_B = 203,
		ShaderProgram_TerrainPatchVertexYFetch = 204,
		ShaderProgram_TerrainMeshScatteringYFetch = 205,
		ShaderProgram_TexYCrCbA = 206,
		ShaderProgram_RgbSeparation = 207,
		ShaderProgram_Distort = 208,
		ShaderProgram_DiffusionDofComputeRadius = 209,
		ShaderProgram_DiffusionDofTridiagonalFill = 210,
		ShaderProgram_DiffusionDofForwardCR = 211,
		ShaderProgram_DiffusionDofBackwardCR = 212,
		ShaderProgram_DiffusionDofSolveFinal = 213,
		ShaderProgram_DiffusionDofOutputPS = 214,
		ShaderProgram_DiffusionDofLinearRadiusPS = 215,
		ShaderProgram_DiffusionDofNonLinearRadiusPS = 216,
		ShaderProgram_DiffusionDofDetectForegroundPS = 217,
		ShaderProgram_DiffusionDofCombineForegroundPS = 218,
		ShaderProgram_DiffusionDofBlurXForegroundPS = 219,
		ShaderProgram_DiffusionDofBlurYForegroundPS = 220,
		ShaderProgram_Ui_DetailTexturedMinimap = 221,
		ShaderProgramCount = 222
	}

}
