<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>$(SolutionDir)\bin\$(Configuration)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Release;Debug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Frostbite\Bundles\**" />
    <Compile Remove="Frostbite\Storage\**" />
    <EmbeddedResource Remove="Frostbite\Bundles\**" />
    <EmbeddedResource Remove="Frostbite\Storage\**" />
    <None Remove="Frostbite\Bundles\**" />
    <None Remove="Frostbite\Storage\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimeLibLite\RimeLibLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>