///////////////////////////////////////////////////////////////
//                                                           //
// This is an automatically generated file.                  //
// Do *NOT* modify unless you really know what you're doing. //
//                                                           //
///////////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Collections.Generic;
using Newtonsoft.Json;
using RimeLib.IO;
using RimeLib.Frostbite.Core;
using RimeLib.Serialization.Attributes;
using RimeLib.Serialization;


namespace fb.VeniceShared;

[ContainerType(1, 4)]
public enum StatEvent : int
{
	StatEvent_Kill = 0,
	StatEvent_Kill_In_X = 1,
	StatEvent_Kill_As_X = 2,
	StatEvent_Kill_As_HVT_Bonus = 3,
	StatEvent_Kill_On_X = 4,
	StatEvent_KillWith_X = 5,
	StatEvent_KillWith_X_As_Y = 6,
	StatEvent_KillWith_X_On_Y = 7,
	StatEvent_KillDistance = 8,
	StatEvent_KillOf_X_As_Y = 9,
	StatEvent_KillOf_X_In_Y = 10,
	StatEvent_TeamKill = 11,
	StatEvent_PaybackKill = 12,
	StatEvent_AvengerKill = 13,
	StatEvent_TeamAvengerKill = 14,
	StatEvent_SquadAvengerKill = 15,
	StatEvent_SaviorKill = 16,
	StatEvent_TeamSaviorKill = 17,
	StatEvent_SquadSaviorKill = 18,
	StatEvent_DriverAssist = 19,
	StatEvent_PassengerAssist = 20,
	StatEvent_SquadPassengerAssist = 21,
	StatEvent_RoadKill = 22,
	StatEvent_Death = 23,
	StatEvent_MultiKill = 24,
	StatEvent_MultiKill_On_X = 25,
	StatEvent_PostMortemKill = 26,
	StatEvent_AdrenalineKill = 27,
	StatEvent_AdrenalineKill_On_X = 28,
	StatEvent_KillStreak = 29,
	StatEvent_KillStreakX = 30,
	StatEvent_TimedKillStreak = 31,
	StatEvent_TimedKillStreak_On_X = 32,
	StatEvent_CancelKillStreak = 33,
	StatEvent_Comeback = 34,
	StatEvent_SquadWipe = 35,
	StatEvent_NemesisKill = 36,
	StatEvent_NemesisKillX = 37,
	StatEvent_CancelNemesisKill = 38,
	StatEvent_SecondsAs_X = 39,
	StatEvent_SecondsWith_X = 40,
	StatEvent_SecondsIn_X = 41,
	StatEvent_SecondsOn_X = 42,
	StatEvent_VehicleDamage_X = 43,
	StatEvent_MobilityCriticalHit_X = 44,
	StatEvent_MobilityKill_X = 45,
	StatEvent_FirepowerCriticalHit_X = 46,
	StatEvent_FirepowerKill_X = 47,
	StatEvent_Destroy_X = 48,
	StatEvent_Destroy_X_As_Y = 49,
	StatEvent_Destroy_X_In_Y = 50,
	StatEvent_Destroy_X_On_Y = 51,
	StatEvent_DestroyWith_X_As_Y = 52,
	StatEvent_Destroy_X_With_Y = 53,
	StatEvent_DestroyExplosives = 54,
	StatEvent_Disabled_X = 55,
	StatEvent_KillOfWith_X_As_Y = 56,
	StatEvent_TaggedDamageAssist_X = 57,
	StatEvent_SquadTaggedDamageAssist_X = 58,
	StatEvent_TaggedDestroy_X = 59,
	StatEvent_SquadTaggedDestroy_X = 60,
	StatEvent_Tagged_X = 61,
	StatEvent_SuppressWith_X_As_Y = 62,
	StatEvent_Level_X_Completed_Y_Difficulty = 63,
	StatEvent_Level_X_Completed_Y_Difficulty_WithTimeValue = 64,
	StatEvent_CleanLevel_X_Completed = 65,
	StatEvent_RoundOverOutcome_X_On_Y = 66,
	StatEvent_Rounds = 67,
	StatEvent_Headshot_X_With_Y = 68,
	StatEvent_HeadshotAs_X_With_Y = 69,
	StatEvent_HeadshotDistance_With_X = 70,
	StatEvent_Headshot_On_X = 71,
	StatEvent_SelfHeal = 72,
	StatEvent_BestSquad = 73,
	StatEvent_ShotsFired_With_X = 74,
	StatEvent_ShotsHit_With_X = 75,
	StatEvent_SpotAssist = 76,
	StatEvent_TeamSpotAssist = 77,
	StatEvent_SquadSpotAssist = 78,
	StatEvent_RadarAssist = 79,
	StatEvent_TeamRadarAssist = 80,
	StatEvent_SquadRadarAssist = 81,
	StatEvent_SuppressionAssist = 82,
	StatEvent_SquadSuppressionAssist = 83,
	StatEvent_Heal = 84,
	StatEvent_TeamHeal = 85,
	StatEvent_SquadHeal = 86,
	StatEvent_Revive = 87,
	StatEvent_TeamRevive = 88,
	StatEvent_SquadRevive = 89,
	StatEvent_ReviveAccepted = 90,
	StatEvent_TeamReviveAccepted = 91,
	StatEvent_SquadReviveAccepted = 92,
	StatEvent_ManDownRevive = 93,
	StatEvent_Resupply = 94,
	StatEvent_TeamResupply = 95,
	StatEvent_SquadResupply = 96,
	StatEvent_KillAssist = 97,
	StatEvent_KillAssistAsKill = 98,
	StatEvent_SquadKillAssistAsKill = 99,
	StatEvent_Repair = 100,
	StatEvent_TeamRepair = 101,
	StatEvent_SquadRepair = 102,
	StatEvent_VehicleDestroyAssist = 103,
	StatEvent_TreeDestroyed = 104,
	StatEvent_WallDestroyed = 105,
	StatEvent_CapturingCapturePoint = 106,
	StatEvent_CaptureCapturePoint = 107,
	StatEvent_NeutralizeCapturePoint = 108,
	StatEvent_CapturePointDefense = 109,
	StatEvent_CapturePointAttack = 110,
	StatEvent_CapturePointLeaderBonus = 111,
	StatEvent_CapturePointDominationBonus = 112,
	StatEvent_CrateInteraction = 113,
	StatEvent_CrateArmed = 114,
	StatEvent_CrateDisarmed = 115,
	StatEvent_CrateDestroyed = 116,
	StatEvent_CrateDefendKill = 117,
	StatEvent_CrateAttackKill = 118,
	StatEvent_BombPickedUp = 119,
	StatEvent_BombDelivered = 120,
	StatEvent_BombDeliveredAssist = 121,
	StatEvent_BombCarrierKilled = 122,
	StatEvent_BombPossession = 123,
	StatEvent_OrderBonus = 124,
	StatEvent_OrderFollowed = 125,
	StatEvent_CommanderOrderAccepted = 126,
	StatEvent_CommanderTomahawkLaunched = 127,
	StatEvent_CommanderTomahawkDamaged = 128,
	StatEvent_CommanderTomahawkDestroyed = 129,
	StatEvent_CommanderScanAssist = 130,
	StatEvent_CommanderHVTMarked = 131,
	StatEvent_CommanderHVTKilled = 132,
	StatEvent_CommanderHVTEliminated = 133,
	StatEvent_CommanderEarlyWarningIssued = 134,
	StatEvent_CommanderSquadPromoted = 135,
	StatEvent_CommanderSquadReinforced = 136,
	StatEvent_CommanderGunshipDeployed = 137,
	StatEvent_CommanderGunshipKillAssist = 138,
	StatEvent_CommanderUnanimousSupport = 139,
	StatEvent_CommanderVehicleDropUsed = 140,
	StatEvent_CommanderSupplyDropUsed = 141,
	StatEvent_CommanderEMPBonus = 142,
	StatEvent_UniqueAward = 143,
	StatEvent_DogTag = 144,
	StatEvent_DogTag_On_X = 145,
	StatEvent_DogTagSavior = 146,
	StatEvent_DogTagPayback = 147,
	StatEvent_SquadSpawn = 148,
	StatEvent_SquadSpawnOnRemoteVehicle_X = 149,
	StatEvent_SquadSpawnOnEquipment = 150,
	StatEvent_DriverSpawnBonus = 151,
	StatEvent_SquadSpawnLastAlive = 152,
	StatEvent_Suicide = 153,
	StatEvent_AISquadKill = 154,
	StatEvent_AISquadKill_On_X = 155,
	StatEvent_GainAward_X = 156,
	StatEvent_PlayerScoreboardPosition_X = 157,
	StatEvent_GainedHighestRank = 158,
	StatEvent_Rank_X = 159,
	StatEvent_GainedHighestUnlockInBucket_X = 160,
	StatEvent_ConsumableUnlocked = 161,
	StatEvent_Misc_X_and_Y = 162,
	StatEvent_TotalScoreOn_X_Difficulty_Y = 163,
	StatEvent_Score_On_X = 164,
	StatEvent_CTF_Capture = 165,
	StatEvent_CTF_CaptureStreak = 166,
	StatEvent_CTF_CaptureAssist = 167,
	StatEvent_CTF_PickUp = 168,
	StatEvent_CTF_PickUpAssist = 169,
	StatEvent_CTF_Return = 170,
	StatEvent_CTF_CarrierAssist = 171,
	StatEvent_CTF_CarrierAssistStreak = 172,
	StatEvent_CTF_FlagTransporter_In_X = 173,
	StatEvent_CTF_CarrierSavior = 174,
	StatEvent_CTF_CarrierSuppression = 175,
	StatEvent_CTF_CarrierKiller = 176,
	StatEvent_CTF_CarrierKillAssist = 177,
	StatEvent_CTF_CarrierHeal = 178,
	StatEvent_StartedFire = 179,
	StatEvent_StartedFire_With_X = 180,
	StatEvent_DamageAreaKill = 181,
	StatEvent_DamageAreaKill_On_X = 182,
	StatEvent_Kill_In_X_On_Y = 183,
	StatEvent_CHLK_NewLink = 184,
	StatEvent_CHLK_DoubleLink = 185,
	StatEvent_CHLK_BreakLink = 186,
	StatEvent_CHLK_IncreaseLinkCount = 187,
	StatEvent_CHLK_DecreaseLinkCount = 188,
	StatEvent_CHLK_BreakTwoLink = 189,
	StatEvent_CHLK_LinkAttack = 190,
	StatEvent_CHLK_LinkDefense = 191,
	StatEvent_Gunmaster_Level = 192,
	StatEvent_Gunmaster_Winner = 193,
	StatEvent_ActiveSpot_In_X = 194,
	StatEvent_KillWith_X_While_Swimming = 195,
	StatEvent_RoundOverOutcome_X_On_Level_Y = 196,
	StatEvent_SecondsIn_X_Airborne = 197,
	StatEvent_DistanceAs_X = 198,
	StatEvent_DistanceIn_X = 199,
	StatEvent_ExplosiveDamageEnemyWith_X = 200,
	StatEvent_DestroyDecoyPack = 201,
	StatEvent_ConsumableUnlocked_X = 202,
	StatEvent_Invalid = 203,
	StatEvent_Damage = 204,
	StatEvent_LAST_ITEM = 205,
}

