using fb;
using RimeLib.Content.Frostbite;
using RimeLib.Content.Mounting;
using RimeLib.Frostbite;
using RimeLib.Frostbite.Core;
using RimeLib.IO;
using RimeLib.Math;
using RimeLib.Mesh.Frostbite;
using SharpGLTF.Geometry;
using SharpGLTF.Geometry.VertexTypes;
using SharpGLTF.Materials;
using SharpGLTF.Scenes;
using SharpGLTF.Schema2;
using SharpGLTF.Transforms;
using System.Runtime.InteropServices;

namespace RimeLib.Mesh.Frostbite2013_2
{
    public class MeshConverter : IMeshConverter
    {
        public Dictionary<string, GUID> GetChunkGuids(IResourceObject p_Resource)
        {
            if (p_Resource.GetResourceType() != ResourceType.MeshSet)
                throw new ArgumentException($"This converter only supports MeshSet resources but got a {p_Resource.GetResourceType()} resource.");

            Dictionary<string, GUID> keyValues = [];

            using var s_ResourceReader = p_Resource.GetReader();
            var s_Layout = new MeshSetLayout(s_ResourceReader);

            for (var i = 0; i < s_Layout.Lods.Length; i++)
            {
                var s_Lod = s_Layout.Lods[i].Object;
                if (s_Lod is null)
                    continue;

                keyValues.Add(s_Lod.Name.Object ?? $"{s_Lod.DataChunkId.ToString("D")}", s_Lod.DataChunkId);
            }

            return keyValues;
        }

        private ModelRoot CreateModel(IResourceObject p_Resource, IEngineMounter p_Mounter)
        {
            // We will convert the model to SharpGLTF
            var s_MeshList = ConvertToMeshBuilders(p_Resource, p_Mounter);

            var s_SceneBuilder = new SceneBuilder();

            foreach (var s_MeshBuilder in s_MeshList)
                s_SceneBuilder.AddRigidMesh(s_MeshBuilder, AffineTransform.Identity);

            return s_SceneBuilder.ToGltf2();
        }

        public void ConvertToBlenderScript(IResourceObject p_Resource, IEngineMounter p_Mounter, string p_OutputFilePath)
        {
            throw new NotImplementedException();
        }

        public void ConvertToGlb(IResourceObject p_Resource, IEngineMounter p_Mounter, string p_OutputFilePath)
        {
            var s_Model = CreateModel(p_Resource, p_Mounter);

            // Save to file
            s_Model.SaveGLB(p_OutputFilePath, new WriteSettings() { JsonIndented = true });
        }

        public void ConvertToGltf(IResourceObject p_Resource, IEngineMounter p_Mounter, string p_OutputFilePath)
        {
            var s_Model = CreateModel(p_Resource, p_Mounter);

            // Save to file
            s_Model.SaveGLTF(p_OutputFilePath, new WriteSettings() { JsonIndented = true });
        }

        public List<MeshBuilder<VertexPosition, VertexTexture1>> ConvertToMeshBuilders(IResourceObject p_Resource, IEngineMounter p_Mounter)
        {
            // Create a list of mesh builders
            var s_MeshList = new List<MeshBuilder<VertexPosition, VertexTexture1>>();

            // Check the resource type
            /*if (p_Resource.GetResourceType() != ResourceType.MeshSet)
                throw new InvalidDataException("Resource type is not MeshSet");*/

            // Get a reader to the object
            using var s_ResourceReader1 = p_Resource.GetReader();
            var s_Data = s_ResourceReader1.ReadBytes((int)s_ResourceReader1.Length);
            using var s_ResourceReader = new RimeReader(new MemoryStream(s_Data));

            // Read the mesh set layout
            var s_MeshSetLayout = new MeshSetLayout(s_ResourceReader);

#if DEBUG
            // Extra debug information
            Console.WriteLine($"Mesh Type: {s_MeshSetLayout.MeshType}");
            Console.WriteLine($"Mesh LODs: {s_MeshSetLayout.LodCount}");
            Console.WriteLine($"Mesh Name: {s_MeshSetLayout.Name.Object}");
            Console.WriteLine($"Mesh Subsets: {s_MeshSetLayout.TotalSubsetCount}");
#endif

            // Create a new GLTF model
            var s_Model = ModelRoot.CreateModel();

            // Set our exported information
            s_Model.Asset.Generator = "Generated by RimeLib (c) 2020";
            s_Model.Asset.Copyright =
                "Exported by Rime (c) kiwidoggie productions 2017-2020, models copyright respective ip owners, not for redistribution";

            // Create a default scene
            var s_Scene = s_Model.UseScene("default");

            // We will set each color as random
            var s_Random = new Random();

            // Iterate through all of the lods
            for (var s_LodIndex = 0; s_LodIndex < s_MeshSetLayout.LodCount; s_LodIndex++)
            {
                // This is a hack to keep it at the highest LOD possible
                // We can ignore this without issue
                if (s_LodIndex != 0)
                    continue;

                // TODO: Need to verify that this still works as intended
                var s_MeshLayout = s_MeshSetLayout.Lods[s_LodIndex].Object;
                if (s_MeshLayout is null)
                    throw new NullReferenceException("MeshLayout is null");

                // Get the LOD name
                var s_LodName = s_MeshLayout.ShortName.Object;

#if DEBUG
                Console.WriteLine($"Dumping LOD {s_LodIndex} - {s_LodName}.");
#endif

                // Check if the assumptions are correct
                if (s_MeshLayout.CategorySubsetIndices.Length != /*(int)MeshSubsetCategory.Count*/ 4)
                    throw new InvalidDataException("MeshSubsetCategory count is invalid.");

                // Get the data chunk
                var s_MeshChunkId = s_MeshLayout.DataChunkId;
                if (!p_Mounter.TryGetChunk(s_MeshChunkId, out IMountedObject<IChunkVariant> p_MeshChunk))
                {
#if DEBUG
                    Console.WriteLine($"Mesh chunk {s_MeshChunkId} does not exist.");
#endif
                    continue;
                }

                using var s_ChunkReader1 = p_MeshChunk.FirstVariant.GetReader();
                var s_ChunkData = s_ChunkReader1.ReadBytes((int)s_ChunkReader1.Length);
                using var s_ChunkReader = new RimeReader(new MemoryStream(s_ChunkData));

                var s_VertexChunkData = s_ChunkReader.ReadBytes((int)s_MeshLayout.VertexDataSize);
                var s_PrimitiveChunkData = s_ChunkReader.ReadBytes((int)s_MeshLayout.IndexDataSize);

                // Hold our subsets
                var s_SubsetsDict = new Dictionary<MeshSubset, List<byte[]>>();

                var s_SubsetsList = new List<MeshSubset>();
                var s_VertexDataList = new List<byte[]>();
                var s_CurrentVertexCount = 0;
                var s_CurrentVertexSize = 0;

                using var s_VertexChunkReader = new RimeReader(new MemoryStream(s_VertexChunkData));

                var s_VertexBitmask = new bool[s_VertexChunkData.Length];

                for (var s_SubsetIndex = 0; s_SubsetIndex < s_MeshLayout.Subsets.Count; s_SubsetIndex++)
                {
                    var s_Subset = s_MeshLayout.Subsets.Get[s_SubsetIndex];

                    // Get the vertex stride, this should be the same as the current stream (elements per vertex) size
                    var s_VertexStride = s_Subset.VertexStride;

                    s_VertexChunkReader.Seek(s_Subset.VertexOffset, SeekOrigin.Begin);

                    // Hold a list for all of our vertex data
                    var s_Set = new List<byte[]>();

                    // Iterate through each of the verticies
                    for (var s_VertexIndex = 0; s_VertexIndex < s_Subset.VertexCount; ++s_VertexIndex)
                    {
                        for (var i = 0; i < s_VertexStride; ++i)
                            s_VertexBitmask[s_VertexChunkReader.Position + i] = true;

                        // Read out the vertex information
                        var s_Bytes = s_VertexChunkReader.ReadBytes(s_VertexStride);

                        // Add this array of bytes (of size vertex stride)
                        s_VertexDataList.Add(s_Bytes);
                        s_Set.Add(s_Bytes);

                        s_CurrentVertexCount++;
                        s_CurrentVertexSize += s_VertexStride;
                    }

                    s_SubsetsDict.Add(s_Subset, s_Set);
                    s_SubsetsList.Add(s_Subset);
                }

                // Hold the subset + parsed vertex information
                var s_ParsedSubsets = new Dictionary<MeshSubset, List<Dictionary<VertexElementUsage, dynamic>>>();

                // Iterate through each of the subsets + the raw data
                for (var s_SubsetIndex = 0; s_SubsetIndex < s_SubsetsDict.Count; s_SubsetIndex++)
                {
                    // Get the subset and data pair
                    var s_SubsetsPair = s_SubsetsDict.ElementAt(s_SubsetIndex);

                    var s_SubsetKey = s_SubsetsPair.Key;
                    var s_SubsetValue = s_SubsetsPair.Value;

                    // Get the geometry descriptor
                    var s_GeometryDesc = s_SubsetKey.GeometryDeclarationDesc;

                    // Iterate all vertices that are for this model
                    if (s_SubsetValue.Count != s_SubsetKey.VertexCount)
                        throw new Exception("vertex count does not match number of verts read");

                    // Parse all of the data
                    var s_VerticiesNiceList = new List<Dictionary<VertexElementUsage, dynamic>>();
                    for (var s_VertexIndex = 0; s_VertexIndex < s_SubsetValue.Count; ++s_VertexIndex)
                    {
                        var s_VertexData = s_SubsetValue[s_VertexIndex];

                        using var s_VertexReader = new RimeReader(new MemoryStream(s_VertexData));

                        var s_Dict = new Dictionary<VertexElementUsage, dynamic>();

                        foreach (var s_Element in s_GeometryDesc.Elements)
                        {
                            s_VertexReader.Seek(s_Element.Offset, SeekOrigin.Begin);

                            // Iterate each element and check the format and set to the usage
                            // There should not be more than one of the same kind of usage here
                            switch (s_Element.Format)
                            {
                                case VertexElementFormat.VertexElementFormat_None:
                                    break;
                                // Halfs
                                case VertexElementFormat.VertexElementFormat_Half:
                                    s_Dict[s_Element.Usage] = RimeMath.HalfToFloat(s_VertexReader.ReadUInt16());
                                    break;
                                case VertexElementFormat.VertexElementFormat_Half2:
                                    s_Dict[s_Element.Usage] = (RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()),
                                        RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()));
                                    break;
                                case VertexElementFormat.VertexElementFormat_Half3:
                                    s_Dict[s_Element.Usage] = (RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()),
                                        RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()),
                                        RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()));
                                    break;
                                case VertexElementFormat.VertexElementFormat_Half4:
                                    s_Dict[s_Element.Usage] = (RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()),
                                        RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()),
                                        RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()),
                                        RimeMath.HalfToFloat(s_VertexReader.ReadUInt16()));
                                    break;

                                // Bytes
                                case VertexElementFormat.VertexElementFormat_UByteN:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadByte();
                                    break;
                                case VertexElementFormat.VertexElementFormat_Byte4: // Should be signed byte
                                case VertexElementFormat.VertexElementFormat_Byte4N:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadBytes(4);
                                    break;
                                case VertexElementFormat.VertexElementFormat_UByte4:
                                case VertexElementFormat.VertexElementFormat_UByte4N:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadBytes(4);
                                    break;

                                // Floats
                                case VertexElementFormat.VertexElementFormat_Float:
                                    s_Dict[s_Element.Usage] = s_VertexReader.ReadSingle();
                                    break;
                                case VertexElementFormat.VertexElementFormat_Float2:
                                    s_Dict[s_Element.Usage] = (s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle());
                                    break;
                                case VertexElementFormat.VertexElementFormat_Float3:
                                    s_Dict[s_Element.Usage] = (s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle(),
                                        s_VertexReader.ReadSingle());
                                    break;
                                case VertexElementFormat.VertexElementFormat_Float4:
                                    s_Dict[s_Element.Usage] = (s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle(),
                                        s_VertexReader.ReadSingle(), s_VertexReader.ReadSingle());
                                    break;
                                default:
                                    Console.WriteLine($"Unknown Format usage {s_Element.Format}");
                                    throw new Exception($"Unknown format usage {s_Element.Format}");
                            }
                        }

                        s_VerticiesNiceList.Add(s_Dict);
                    }

                    // Verify that we have parsed all the vertices
                    if (s_VerticiesNiceList.Count != s_SubsetKey.VertexCount)
                        throw new Exception("Unable to convert all vertices");

                    // Add to the new map of subset + parsed vertices
                    s_ParsedSubsets.Add(s_SubsetKey, s_VerticiesNiceList);
                }

                // Now order the mesh subset category + (subset + parsed vert data)
                var s_Categories =
                    new Dictionary<MeshSubsetCategory,
                        List<KeyValuePair<MeshSubset, List<Dictionary<VertexElementUsage, dynamic>>>>>();
                for (var s_CategoryIndex = 0;
                     s_CategoryIndex < s_MeshLayout.CategorySubsetIndices.Length;
                     ++s_CategoryIndex)
                {
                    // Get the list of subsets per-category
                    var s_SubsetIndicies = s_MeshLayout.CategorySubsetIndices[s_CategoryIndex].Get;

                    // Hold a list of subsets + parsed verts
                    var s_SubsetPairList =
                        new List<KeyValuePair<MeshSubset, List<Dictionary<VertexElementUsage, dynamic>>>>();
                    foreach (var s_SubsetIndex in s_SubsetIndicies)
                    {
                        // Example: Opaque = 0x1, 0x2 (subset index)
                        var s_SubsetPair = s_ParsedSubsets.ElementAt(s_SubsetIndex);

                        s_SubsetPairList.Add(s_SubsetPair);
                    }

                    // Add to the dictionary for subset category, (subsets + vertex data)[]
                    s_Categories.Add((MeshSubsetCategory)s_CategoryIndex, s_SubsetPairList);
                }

                // We only want to get the opaque meshes, TODO: Iterate through everything
                var s_OpaqueSubsets = s_Categories[0]; // s_Categories[MeshSubsetCategory.Opaque];

                // TODO: Hold list of subset + parsed verts + primitives

                // Open up a reader for our primitives
                using (var s_IndexReader = new RimeReader(new MemoryStream(s_PrimitiveChunkData)))
                {
                    // Iterate each subset pair
                    foreach (var s_SubsetPair in s_OpaqueSubsets)
                    {
                        // Get the subset
                        var s_SubsetKey = s_SubsetPair.Key;
                        var s_SubsetValue = s_SubsetPair.Value;

                        // Calculate the start offset in the index buffer
                        var s_SubsetStartIndex = s_SubsetKey.StartIndex;

                        // Validate the start offset
                        var s_SubsetStartOffset = Marshal.SizeOf<ushort>() * s_SubsetStartIndex;
                        if (s_SubsetStartOffset >= s_IndexReader.Length)
                            throw new Exception("subset start offset");

                        // Calculate and verify the end offset (that it's in-bounds)
                        var s_SubsetEndOffset =
                            (Marshal.SizeOf<ushort>() * 3) * s_SubsetKey.PrimitiveCount; // * 3 for X, Y, Z
                        if (s_SubsetEndOffset > s_IndexReader.Length)
                            throw new Exception("subset end offset");

                        // Hold our index list
                        var s_PrimitiveList = new List<(ushort, ushort, ushort)>();
                        switch (s_SubsetKey.PrimitiveType)
                        {
                            // If we are parsing a triangle list, then read out the X, Y, Z indices
                            case RimeLib.Mesh.Frostbite.PrimitiveType.PrimitiveType_TriangleList:
                                s_IndexReader.Seek(s_SubsetStartOffset, SeekOrigin.Begin);
                                for (var s_PrimitiveIndex = 0;
                                     s_PrimitiveIndex < s_SubsetKey.PrimitiveCount;
                                     ++s_PrimitiveIndex)
                                    s_PrimitiveList.Add((s_IndexReader.ReadUInt16(), s_IndexReader.ReadUInt16(),
                                        s_IndexReader.ReadUInt16()));
                                break;
                            default:
                                throw new Exception("unimplemented primitive type");
                        }

                        // Continue with creating the gltf format
                        var s_RandomColor = new System.Numerics.Vector4((float)s_Random.NextDouble(), (float)s_Random.NextDouble(),
                            (float)s_Random.NextDouble(), 1.0f);
                        var s_DebugMaterial = new MaterialBuilder(s_SubsetKey.MaterialName.Object ?? "")
                            .WithMetallicRoughnessShader().WithChannelParam(KnownChannel.BaseColor, KnownProperty.RGBA, s_RandomColor);

                        // Create a new GLTF mesh
                        var s_Mesh =
                            new MeshBuilder<VertexPosition, VertexTexture1>(
                                $"MeshSubsetCategory_{s_MeshLayout.ShortName.Object}_Lod{s_LodIndex}");
                        var s_Primitive = s_Mesh.UsePrimitive(s_DebugMaterial);

                        // Iterate through all primitives
                        for (var s_PrimitiveIndex = 0; s_PrimitiveIndex < s_PrimitiveList.Count; ++s_PrimitiveIndex)
                        {
                            var s_PrimitiveIndices = s_PrimitiveList[s_PrimitiveIndex];

                            var s_FirstIndex = s_PrimitiveIndices.Item1;
                            if (s_FirstIndex > s_SubsetValue.Count)
                                throw new Exception("first index oob");

                            var s_FirstVertex = s_SubsetValue[s_FirstIndex];
                            if (!s_FirstVertex.TryGetValue(VertexElementUsage.VertexElementUsage_Pos,
                                    out dynamic s_FirstVertexPos))
                                continue;


                            var s_SecondIndex = s_PrimitiveIndices.Item2;
                            if (s_SecondIndex > s_SubsetValue.Count)
                                throw new Exception("second index oob");

                            var s_SecondVertex = s_SubsetValue[s_SecondIndex];
                            if (!s_SecondVertex.TryGetValue(VertexElementUsage.VertexElementUsage_Pos,
                                    out dynamic s_SecondVertexPos))
                                continue;

                            var s_ThirdIndex = s_PrimitiveIndices.Item3;
                            if (s_ThirdIndex > s_SubsetValue.Count)
                                throw new Exception("third index oob");

                            var s_ThirdVertex = s_SubsetValue[s_ThirdIndex];
                            if (!s_ThirdVertex.TryGetValue(VertexElementUsage.VertexElementUsage_Pos,
                                    out dynamic s_ThirdVertexPos))
                                continue;


                            var s_FirstPosition = new VertexPosition(s_FirstVertexPos.Item1, s_FirstVertexPos.Item2,
                                s_FirstVertexPos.Item3);
                            var s_SecondPosition = new VertexPosition(s_SecondVertexPos.Item1, s_SecondVertexPos.Item2,
                                s_SecondVertexPos.Item3);
                            var s_ThirdPosition = new VertexPosition(s_ThirdVertexPos.Item1, s_ThirdVertexPos.Item2,
                                s_ThirdVertexPos.Item3);


                            if (s_FirstVertex.TryGetValue(VertexElementUsage.VertexElementUsage_TexCoord0,
                                    out dynamic s_FirstVertexTexture) &&
                                s_SecondVertex.TryGetValue(VertexElementUsage.VertexElementUsage_TexCoord0,
                                    out dynamic s_SecondVertexTexture) &&
                                s_ThirdVertex.TryGetValue(VertexElementUsage.VertexElementUsage_TexCoord0,
                                    out dynamic s_ThirdVertexTexture))
                            {
                                var s_FirstTexture = new VertexTexture1(
                                    new System.Numerics.Vector2(s_FirstVertexTexture.Item1, s_FirstVertexTexture.Item2));
                                var s_SecondTexture = new VertexTexture1(
                                    new System.Numerics.Vector2(s_SecondVertexTexture.Item1, s_SecondVertexTexture.Item2));
                                var s_ThirdTexture = new VertexTexture1(
                                    new System.Numerics.Vector2(s_ThirdVertexTexture.Item1, s_ThirdVertexTexture.Item2));

                                s_Primitive.AddTriangle((s_FirstPosition, s_FirstTexture),
                                    (s_SecondPosition, s_SecondTexture), (s_ThirdPosition, s_ThirdTexture));
                            }
                            else
                            {
                                //Console.WriteLine("No texcoords");
                                s_Primitive.AddTriangle(s_FirstPosition, s_SecondPosition, s_ThirdPosition);
                            }
                        }

                        s_MeshList.Add(s_Mesh);
                    }
                }
            }

            return s_MeshList;

        }

        public void ConvertToObj(IResourceObject p_Resource, IEngineMounter p_Mounter, string p_OutputFilePath)
        {
            var s_Model = CreateModel(p_Resource, p_Mounter);

            // Save to file
            s_Model.SaveAsWavefront(p_OutputFilePath);
        }

        public EngineType[] GetSupportedEngines()
        {
            return [EngineType.Frostbite2013_2];
        }
    }
}
