name: build

on:
  push:
    branches: [ master, development ]

env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: |
        dotnet publish .\Utils\RimeREPL\RimeREPL.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Texture.Frostbite2_0\RimeLib.Texture.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Shader.Frostbite2_0\RimeLib.Shader.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Havok.Frostbite2_0\RimeLib.Havok.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Mesh.Frostbite2_0\RimeLib.Mesh.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Toolkit\RimeLib.Toolkit.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Toolkit.Frostbite2_0\RimeLib.Toolkit.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: Rime-win-x64
        path: |
          dist/*