name: build

on:
  push:
    branches: [ master ]

env:
  DOTNET_VERSION: '6.0.201' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: |
        dotnet build --configuration Release
        dotnet publish .\Utils\RimeREPL\RimeREPL.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Content.Frostbite2_0\RimeLib.Content.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Texture.Frostbite2_0\RimeLib.Texture.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true
        dotnet publish .\RimeLib.Serialization.Frostbite2_0\RimeLib.Serialization.Frostbite2_0.csproj -c Release -o ./dist -r win-x64 --self-contained true /p:UseAppHost=true

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: Rime-win-x64
        path: |
          dist/*