namespace RimeLib.Texture.Frostbite2_0.Frostbite;

public enum TextureFormat : uint
{
    TextureFormat_DXT1,
    TextureFormat_DXT3,
    TextureFormat_DXT5,
    TextureFormat_DXT5A,
    TextureFormat_DXN,
    TextureFormat_RGB565,
    TextureFormat_RGB888,
    TextureFormat_ARGB1555,
    TextureFormat_ARGB4444,
    TextureFormat_ARGB8888,
    TextureFormat_L8,
    TextureFormat_L16,
    TextureFormat_ABGR16,
    TextureFormat_ABGR16F,
    TextureFormat_ABGR32F,
    TextureFormat_R16F,
    TextureFormat_R32F,
    TextureFormat_NormalDXN,
    TextureFormat_NormalDXT1,
    TextureFormat_NormalDXT5,
    TextureFormat_NormalDXT5RGA,
    TextureFormat_RG8,
    TextureFormat_GR16,
    TextureFormat_GR16F,
    TextureFormat_D16,
    TextureFormat_D24S8,
    TextureFormat_D24FS8,
    TextureFormat_D32F,
    TextureFormat_ABGR32,
    TextureFormat_GR32F,
    TextureFormat_A2R10G10B10,
    TextureFormat_Unknown,
}